/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
namespace POCO
{
public class Data_Retention_Policy
{
 public Int32 Policy_Id;
 public Int32? Location_ID;
 public string Data_Type;
 public Int32? Retention_Period_Days;
 public bool? Auto_Anonymize;
 public bool? Region_Lock;
 public DateTime? Enforced_From;
 public string Notes;
 public byte Is_Active;
 public DateTime Created_Date;
 public Int32 Created_By;
 public DateTime? Modified_Date;
 public Int32? Modified_By;
 public Int64? Audit_Id;
 public string User_IP;
 public Int32 Site_Id;
public List<Data_Retention_Policy> lstData_Retention_Policy;
}
}
/*****************************************************************************************************************/

