/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
namespace POCO
{
public class Department
{
 public Int32 DepartmentId;
 public Int32? Location_ID;
 public string DepartmentName;
 public string DepartmentCode;
 public Int32? ParentID;
 public Int32? ManagerID;
 public string PhoneNumber;
 public string Email;
 public Decimal? Budget;
 public DateTime? EstablishedDate;
 public string Status;
 public DateTime? CreatedAt;
 public string CreatedBy;
 public DateTime? ModifiedAt;
 public string ModifiedBy;
public List<Department> lstDepartment;
}
}
/*****************************************************************************************************************/

