/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
namespace POCO
{
public class Feedback
{
 public Int64 Feedback_Id;
 public Int32? Location_ID;
 public Int32? User_Id;
 public Int32? Match_Id;
 public string Feedback_Type;
 public Int32? Rating;
 public string Comments;
 public DateTime? Submitted_At;
 public byte Is_Active;
 public DateTime Created_Date;
 public Int32 Created_By;
 public DateTime? Modified_Date;
 public Int32? Modified_By;
 public Int64? Audit_Id;
 public string User_IP;
 public Int32 Site_Id;
public List<Feedback> lstFeedback;
}
}
/*****************************************************************************************************************/

