/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
namespace POCO
{
public class Incident_Log
{
 public Int64 Incident_Id;
 public Int32? Location_ID;
 public string Component_Name;
 public string Incident_Type;
 public string Details;
 public DateTime? Detected_At;
 public DateTime? Resolved_At;
 public string Status;
 public Int32? Resolved_By;
 public string Notes;
 public byte Is_Active;
 public DateTime Created_Date;
 public Int32 Created_By;
 public DateTime? Modified_Date;
 public Int32? Modified_By;
 public Int64? Audit_Id;
 public string User_IP;
 public Int32 Site_Id;
public List<Incident_Log> lstIncident_Log;
}
}
/*****************************************************************************************************************/

