/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
namespace POCO
{
public class Manufacturer
{
 public Int32 ManufacturerId;
 public Int32? Location_ID;
 public string ManufacturerCode;
 public string ManufacturerName;
 public string ContactName;
 public string ContactTitle;
 public string PhoneNumber;
 public string Email;
 public string AddressLine1;
 public string AddressLine2;
 public string City;
 public string State;
 public string PostalCode;
 public string Country;
 public string WebsiteURL;
 public string Notes;
 public byte Is_Active;
 public DateTime Created_Date;
 public Int32 Created_By;
 public DateTime? Modified_Date;
 public Int32? Modified_By;
 public Int64? Audit_Id;
 public string User_IP;
 public Int32 Site_Id;
public List<Manufacturer> lstManufacturer;
}
}
/*****************************************************************************************************************/

