/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
namespace POCO
{
public class User_Screen_Right
{
 public Int32 UserRightsId;
 public Int32? UserGroupId;
 public Int32? ScreenId;
 public bool? ViewRights;
 public bool? AddRights;
 public bool? EditRights;
 public bool? DeleteRights;
 public bool? ReportRights;
 public bool Is_Active;
 public DateTime Created_Date;
 public Int32 Created_By;
 public DateTime? Modified_Date;
 public Int32? Modified_By;
 public Int32? Audit_Id;
 public string User_IP;
 public Int32 Site_Id;
public List<User_Screen_Right> lstUser_Screen_Right;
}
}
/*****************************************************************************************************************/

