/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
namespace Utility
{
public static class EntityMapper
{
public struct Entities{
 public const string AI_MODEL = "DataLayer.AI_Model";
 public const string CATEGORY = "DataLayer.Category";
 public const string COMMENTARY_FEED = "DataLayer.Commentary_Feed";
 public const string COMMENTARY_LOG = "DataLayer.Commentary_Log";
 public const string COMMENTARY_SEGMENT = "DataLayer.Commentary_Segment";
 public const string CUSTOM_AUDIENCE_SEGMENT = "DataLayer.Custom_Audience_Segment";
 public const string CUSTOMER = "DataLayer.Customer";
 public const string DATA_RETENTION_POLICY = "DataLayer.Data_Retention_Policy";
 public const string DEPARTMENT = "DataLayer.Department";
 public const string DYNAMIC_PRICING_HISTORY = "DataLayer.Dynamic_Pricing_History";
 public const string EMPLOYEE = "DataLayer.Employee";
 public const string FEEDBACK = "DataLayer.Feedback";
 public const string GROUP = "DataLayer.Group";
 public const string INCIDENT_LOG = "DataLayer.Incident_Log";
 public const string LANGUAGE = "DataLayer.Language";
 public const string LIVE_MATCH = "DataLayer.Live_Match";
 public const string LOCALIZATION_TOKEN = "DataLayer.Localization_Token";
 public const string LOCATION = "DataLayer.Location";
 public const string LOCATION_DETAIL = "DataLayer.Location_Detail";
 public const string LOCATION_TYPE = "DataLayer.Location_Type";
 public const string MANUFACTURER = "DataLayer.Manufacturer";
 public const string MATCH_STAT = "DataLayer.Match_Stat";
 public const string MODEL_TRAINING_JOB = "DataLayer.Model_Training_Job";
 public const string PHYSICALLOCATION = "DataLayer.PhysicalLocation";
 public const string PHYSICALLOCATION_DETAIL = "DataLayer.PhysicalLocation_Detail";
 public const string PHYSICALLOCATION_TYPE = "DataLayer.PhysicalLocation_Type";
 public const string REALTIME_EVENT_QUEUE = "DataLayer.RealTime_Event_Queue";
 public const string REGION_COMPLIANCE = "DataLayer.Region_Compliance";
 public const string RETRAINING_FEEDBACK = "DataLayer.Retraining_Feedback";
 public const string SCREEN = "DataLayer.Screen";
 public const string SETTINGS = "DataLayer.Settings";
 public const string SPONSOR_MESSAGE = "DataLayer.Sponsor_Message";
 public const string SUBCATEGORY = "DataLayer.SubCategory";
 public const string SUBSCRIPTION = "DataLayer.Subscription";
 public const string SUPPLIER = "DataLayer.Supplier";
 public const string SYSTEM_HEALTH_LOG = "DataLayer.System_Health_Log";
 public const string TENANT = "DataLayer.Tenant";
 public const string USER = "DataLayer.User";
 public const string USER_ACTIVITY_LOG = "DataLayer.User_Activity_Log";
 public const string USER_GROUP = "DataLayer.User_Group";
 public const string USER_SCREEN_RIGHT = "DataLayer.User_Screen_Right";
 public const string USER_SESSION_TRACKING = "DataLayer.User_Session_Tracking";
 public const string VENDOR = "DataLayer.Vendor";
 public const string VOICE = "DataLayer.Voice";
 public const string VOICE_PREFERENCE = "DataLayer.Voice_Preference";
}
public struct AI_Model
{
 public const string MODEL_ID = "Model_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string MODEL_TYPE = "Model_Type";
 public const string VERSION = "Version";
 public const string MODEL_SOURCE = "Model_Source";
 public const string STATUS = "Status";
 public const string TRAINED_ON = "Trained_On";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Category
{
 public const string CATEGORYID = "CategoryId";
 public const string LOCATION_ID = "Location_ID";
 public const string CATEGORYNAME = "CategoryName";
 public const string DESCRIPTION = "Description";
 public const string LIFE = "Life";
 public const string IS_CHECKOUT = "Is_Checkout";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Commentary_Feed
{
 public const string FEED_ID = "Feed_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string MATCH_ID = "Match_Id";
 public const string LANGUAGE_CODE = "Language_Code";
 public const string COMMENTARY_TEXT = "Commentary_Text";
 public const string VOICE_PROFILE = "Voice_Profile";
 public const string TIMESTAMP = "Timestamp";
 public const string TONE = "Tone";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Commentary_Log
{
 public const string LOG_ID = "Log_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string FEED_ID = "Feed_Id";
 public const string ENGAGEMENT_SCORE = "Engagement_Score";
 public const string LATENCY_MILLIS = "Latency_Millis";
 public const string SENTIMENT_SCORE = "Sentiment_Score";
 public const string FEEDBACK_TEXT = "Feedback_Text";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Commentary_Segment
{
 public const string SEGMENT_ID = "Segment_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string FEED_ID = "Feed_Id";
 public const string SEGMENT_TEXT = "Segment_Text";
 public const string SEGMENT_TIMESTAMP = "Segment_Timestamp";
 public const string SEGMENT_TYPE = "Segment_Type";
 public const string EMOTION_TAG = "Emotion_Tag";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Custom_Audience_Segment
{
 public const string SEGMENT_ID = "Segment_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string SEGMENT_NAME = "Segment_Name";
 public const string FILTER_LOGIC = "Filter_Logic";
 public const string LANGUAGE_PREFERENCE = "Language_Preference";
 public const string COMMENTARY_MODE = "Commentary_Mode";
 public const string VOICE_ID = "Voice_Id";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Customer
{
 public const string CUSTOMERID = "CustomerId";
 public const string LOCATION_ID = "Location_ID";
 public const string CUSTOMERCODE = "CustomerCode";
 public const string CUSTOMERNAME = "CustomerName";
 public const string CONTACTNAME = "ContactName";
 public const string CONTACTTITLE = "ContactTitle";
 public const string DATEOFBIRTH = "DateOfBirth";
 public const string GENDER = "Gender";
 public const string PHONENUMBER = "PhoneNumber";
 public const string EMAIL = "Email";
 public const string ADDRESSLINE1 = "AddressLine1";
 public const string ADDRESSLINE2 = "AddressLine2";
 public const string CITY = "City";
 public const string STATE = "State";
 public const string POSTALCODE = "PostalCode";
 public const string COUNTRY = "Country";
 public const string WEBSITEURL = "WebsiteURL";
 public const string CUSTOMERSINCE = "CustomerSince";
 public const string ACCOUNTBALANCE = "AccountBalance";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Data_Retention_Policy
{
 public const string POLICY_ID = "Policy_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string DATA_TYPE = "Data_Type";
 public const string RETENTION_PERIOD_DAYS = "Retention_Period_Days";
 public const string AUTO_ANONYMIZE = "Auto_Anonymize";
 public const string REGION_LOCK = "Region_Lock";
 public const string ENFORCED_FROM = "Enforced_From";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Department
{
 public const string DEPARTMENTID = "DepartmentId";
 public const string LOCATION_ID = "Location_ID";
 public const string DEPARTMENTNAME = "DepartmentName";
 public const string DEPARTMENTCODE = "DepartmentCode";
 public const string PARENTID = "ParentID";
 public const string MANAGERID = "ManagerID";
 public const string PHONENUMBER = "PhoneNumber";
 public const string EMAIL = "Email";
 public const string BUDGET = "Budget";
 public const string ESTABLISHEDDATE = "EstablishedDate";
 public const string STATUS = "Status";
 public const string CREATEDAT = "CreatedAt";
 public const string CREATEDBY = "CreatedBy";
 public const string MODIFIEDAT = "ModifiedAt";
 public const string MODIFIEDBY = "ModifiedBy";
}
public struct Dynamic_Pricing_History
{
 public const string PRICING_ID = "Pricing_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string LANGUAGE_CODE = "Language_Code";
 public const string MATCH_ID = "Match_Id";
 public const string STREAM_TYPE = "Stream_Type";
 public const string PRICE_PER_MINUTE = "Price_Per_Minute";
 public const string APPLIED_AT = "Applied_At";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Employee
{
 public const string EMPLOYEEID = "EmployeeId";
 public const string LOCATION_ID = "Location_ID";
 public const string EMPLOYEECODE = "EmployeeCode";
 public const string FIRSTNAME = "FirstName";
 public const string LASTNAME = "LastName";
 public const string MIDDLENAME = "MiddleName";
 public const string DATEOFBIRTH = "DateOfBirth";
 public const string HIREDATE = "HireDate";
 public const string JOBTITLE = "JobTitle";
 public const string DEPARTMENTID = "DepartmentId";
 public const string MANAGERID = "ManagerId";
 public const string SALARY = "Salary";
 public const string GENDER = "Gender";
 public const string PHONENUMBER = "PhoneNumber";
 public const string EMAIL = "Email";
 public const string ADDRESSLINE1 = "AddressLine1";
 public const string ADDRESSLINE2 = "AddressLine2";
 public const string CITY = "City";
 public const string STATE = "State";
 public const string POSTALCODE = "PostalCode";
 public const string COUNTRY = "Country";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Feedback
{
 public const string FEEDBACK_ID = "Feedback_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string USER_ID = "User_Id";
 public const string MATCH_ID = "Match_Id";
 public const string FEEDBACK_TYPE = "Feedback_Type";
 public const string RATING = "Rating";
 public const string COMMENTS = "Comments";
 public const string SUBMITTED_AT = "Submitted_At";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Group
{
 public const string USERGROUPID = "UserGroupId";
 public const string COMPANYID = "CompanyId";
 public const string LOCATION_ID = "Location_ID";
 public const string GROUPNAME = "GroupName";
 public const string DESCRIPTION = "Description";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Incident_Log
{
 public const string INCIDENT_ID = "Incident_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string COMPONENT_NAME = "Component_Name";
 public const string INCIDENT_TYPE = "Incident_Type";
 public const string DETAILS = "Details";
 public const string DETECTED_AT = "Detected_At";
 public const string RESOLVED_AT = "Resolved_At";
 public const string STATUS = "Status";
 public const string RESOLVED_BY = "Resolved_By";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Language
{
 public const string LANGUAGE_CODE = "Language_Code";
 public const string LOCATION_ID = "Location_ID";
 public const string LANGUAGE_NAME = "Language_Name";
 public const string REGION = "Region";
 public const string IS_SUPPORTED = "Is_Supported";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Live_Match
{
 public const string MATCH_ID = "Match_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string SPORT_TYPE = "Sport_Type";
 public const string HOME_TEAM = "Home_Team";
 public const string AWAY_TEAM = "Away_Team";
 public const string MATCH_DATE = "Match_Date";
 public const string BROADCAST_URL = "Broadcast_URL";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Localization_Token
{
 public const string TOKEN_ID = "Token_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string KEY_NAME = "Key_Name";
 public const string LANGUAGE_CODE = "Language_Code";
 public const string LOCALIZED_VALUE = "Localized_Value";
 public const string IS_UI_ONLY = "Is_UI_Only";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Location
{
 public const string LOCATION_ID = "Location_ID";
 public const string TENANTID = "TenantId";
 public const string LOCATIONNAME = "LocationName";
 public const string SHORT_CODE = "Short_Code";
 public const string LONG_CODE = "Long_Code";
 public const string SHORT_NAME = "Short_Name";
 public const string DESCRIPTION = "Description";
 public const string PARENT_LOCATION_ID = "Parent_Location_ID";
 public const string LOCATION_TYPE_ID = "Location_Type_Id";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Location_Detail
{
 public const string LOC_DETAIL_ID = "Loc_Detail_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string DOWNTIME = "Downtime";
 public const string ADDRESSLINE1 = "AddressLine1";
 public const string ADDRESSLINE2 = "AddressLine2";
 public const string CITY = "City";
 public const string STATE = "State";
 public const string COUNTRY = "Country";
 public const string POSTALCODE = "PostalCode";
 public const string FAXNUMBER = "FaxNumber";
 public const string PHONENUMBER1 = "PhoneNumber1";
 public const string PHONENUMBER2 = "PhoneNumber2";
 public const string EMAIL = "Email";
 public const string WEBSITEURL = "WebsiteURL";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Location_Type
{
 public const string LOCATION_TYPE_ID = "Location_Type_Id";
 public const string LOCATIONTYPENAME = "LocationTypeName";
 public const string DESCRIPTION = "Description";
 public const string PARENT_LOCATION_TYPE_ID = "Parent_Location_Type_ID";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Manufacturer
{
 public const string MANUFACTURERID = "ManufacturerId";
 public const string LOCATION_ID = "Location_ID";
 public const string MANUFACTURERCODE = "ManufacturerCode";
 public const string MANUFACTURERNAME = "ManufacturerName";
 public const string CONTACTNAME = "ContactName";
 public const string CONTACTTITLE = "ContactTitle";
 public const string PHONENUMBER = "PhoneNumber";
 public const string EMAIL = "Email";
 public const string ADDRESSLINE1 = "AddressLine1";
 public const string ADDRESSLINE2 = "AddressLine2";
 public const string CITY = "City";
 public const string STATE = "State";
 public const string POSTALCODE = "PostalCode";
 public const string COUNTRY = "Country";
 public const string WEBSITEURL = "WebsiteURL";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Match_Stat
{
 public const string STAT_ID = "Stat_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string MATCH_ID = "Match_Id";
 public const string PLAYER_NAME = "Player_Name";
 public const string EVENT_TYPE = "Event_Type";
 public const string EVENT_DESCRIPTION = "Event_Description";
 public const string TIMESTAMP = "Timestamp";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Model_Training_Job
{
 public const string JOB_ID = "Job_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string MODEL_ID = "Model_Id";
 public const string START_TIME = "Start_Time";
 public const string END_TIME = "End_Time";
 public const string STATUS = "Status";
 public const string TRIGGERED_BY = "Triggered_By";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct PhysicalLocation
{
 public const string PHYSICALLOCATION_ID = "PhysicalLocation_ID";
 public const string LOCATION_ID = "Location_ID";
 public const string PHYSICALLOCATIONNAME = "PhysicalLocationName";
 public const string SHORT_CODE = "Short_Code";
 public const string LONG_CODE = "Long_Code";
 public const string SHORT_NAME = "Short_Name";
 public const string DESCRIPTION = "Description";
 public const string PARENT_PHYSICALLOCATION_ID = "Parent_PhysicalLocation_ID";
 public const string PHYSICALLOCATION_TYPE_ID = "PhysicalLocation_Type_Id";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct PhysicalLocation_Detail
{
 public const string PHYSICALLOC_DETAIL_ID = "PhysicalLoc_Detail_Id";
 public const string PHYSICALLOCATION_ID = "PhysicalLocation_ID";
 public const string DOWNTIME = "Downtime";
 public const string ADDRESSLINE1 = "AddressLine1";
 public const string ADDRESSLINE2 = "AddressLine2";
 public const string CITY = "City";
 public const string STATE = "State";
 public const string COUNTRY = "Country";
 public const string POSTALCODE = "PostalCode";
 public const string FAXNUMBER = "FaxNumber";
 public const string PHONENUMBER1 = "PhoneNumber1";
 public const string PHONENUMBER2 = "PhoneNumber2";
 public const string EMAIL = "Email";
 public const string WEBSITEURL = "WebsiteURL";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct PhysicalLocation_Type
{
 public const string PHYSICALLOCATION_TYPE_ID = "PhysicalLocation_Type_Id";
 public const string PHYSICALLOCATIONTYPENAME = "PhysicalLocationTypeName";
 public const string DESCRIPTION = "Description";
 public const string PARENT_PHYSICALLOCATION_TYPE_ID = "Parent_PhysicalLocation_Type_ID";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct RealTime_Event_Queue
{
 public const string EVENT_ID = "Event_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string MATCH_ID = "Match_Id";
 public const string EVENT_TYPE = "Event_Type";
 public const string EVENT_DATA = "Event_Data";
 public const string PROCESSED = "Processed";
 public const string EVENT_TIMESTAMP = "Event_Timestamp";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Region_Compliance
{
 public const string COMPLIANCE_ID = "Compliance_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string REGION_NAME = "Region_Name";
 public const string REGULATION_NAME = "Regulation_Name";
 public const string RULE_DESCRIPTION = "Rule_Description";
 public const string ENFORCEMENT_LEVEL = "Enforcement_Level";
 public const string APPLIES_TO = "Applies_To";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Retraining_Feedback
{
 public const string FEEDBACK_ID = "Feedback_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string COMMENTARY_SEGMENT_ID = "Commentary_Segment_Id";
 public const string FLAG_TYPE = "Flag_Type";
 public const string COMMENTS = "Comments";
 public const string ANNOTATED_BY = "Annotated_By";
 public const string REVIEWED = "Reviewed";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Screen
{
 public const string SCREENID = "ScreenId";
 public const string LOCATION_ID = "Location_ID";
 public const string SCREENNAME = "ScreenName";
 public const string DESCRIPTION = "Description";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Settings
{
 public const string SETTINGID = "SettingId";
 public const string SETTINGKEY = "SettingKey";
 public const string SETTINGVALUE = "SettingValue";
 public const string DESCRIPTION = "Description";
 public const string MODULE = "Module";
 public const string DATATYPE = "DataType";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Sponsor_Message
{
 public const string MESSAGE_ID = "Message_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string SPONSOR_NAME = "Sponsor_Name";
 public const string LANGUAGE_CODE = "Language_Code";
 public const string MESSAGE_TEXT = "Message_Text";
 public const string PLACEMENT_CONTEXT = "Placement_Context";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct SubCategory
{
 public const string SUBCATEGORYID = "SubCategoryId";
 public const string LOCATION_ID = "Location_ID";
 public const string CATEGORYID = "CategoryId";
 public const string SUBCATEGORYNAME = "SubCategoryName";
 public const string DESRIPTION = "Desription";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Subscription
{
 public const string SUBSCRIPTIONID = "SubscriptionId";
 public const string PLANNAME = "PlanName";
 public const string STATUS = "Status";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
}
public struct Supplier
{
 public const string SUPPLIERID = "SupplierId";
 public const string LOCATION_ID = "Location_ID";
 public const string SUPPLIERCODE = "SupplierCode";
 public const string SUPPLIERNAME = "SupplierName";
 public const string CONTACTNAME = "ContactName";
 public const string CONTACTTITLE = "ContactTitle";
 public const string PHONENUMBER = "PhoneNumber";
 public const string EMAIL = "Email";
 public const string ADDRESSLINE1 = "AddressLine1";
 public const string ADDRESSLINE2 = "AddressLine2";
 public const string CITY = "City";
 public const string STATE = "State";
 public const string POSTALCODE = "PostalCode";
 public const string COUNTRY = "Country";
 public const string WEBSITEURL = "WebsiteURL";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct System_Health_Log
{
 public const string HEALTH_LOG_ID = "Health_Log_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string COMPONENT_NAME = "Component_Name";
 public const string METRIC_NAME = "Metric_Name";
 public const string METRIC_VALUE = "Metric_Value";
 public const string RECORDED_AT = "Recorded_At";
 public const string SEVERITY = "Severity";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Tenant
{
 public const string TENANTID = "TenantId";
 public const string TENANTSECRET = "TenantSecret";
 public const string TENANTNAME = "TenantName";
 public const string CONTACTEMAIL = "ContactEmail";
 public const string SUBSCRIPTIONID = "SubscriptionId";
 public const string SUBSCRIPTIONSTARTDATE = "SubscriptionStartDate";
 public const string SUBSCRIPTIONENDDATE = "SubscriptionEndDate";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
}
public struct User
{
 public const string USERID = "UserId";
 public const string EMPLOYEEID = "EmployeeId";
 public const string USERGROUPID = "UserGroupId";
 public const string LOCATION_ID = "Location_Id";
 public const string USERNAME = "UserName";
 public const string PASSWORD = "Password";
 public const string EMAIL = "Email";
 public const string TEMPPASSWORD = "TempPassword";
 public const string DATERANGEFROM = "DateRangeFrom";
 public const string DATERANGETO = "DateRangeTo";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct User_Activity_Log
{
 public const string LOG_ID = "Log_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string USER_ID = "User_Id";
 public const string ACTIVITY_TYPE = "Activity_Type";
 public const string ACTIVITY_TIMESTAMP = "Activity_Timestamp";
 public const string ADDITIONAL_DATA = "Additional_Data";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct User_Group
{
 public const string USERGROUPRELATIONID = "UserGroupRelationId";
 public const string USERID = "UserId";
 public const string USERGROUPID = "UserGroupId";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct User_Screen_Right
{
 public const string USERRIGHTSID = "UserRightsId";
 public const string USERGROUPID = "UserGroupId";
 public const string SCREENID = "ScreenId";
 public const string VIEWRIGHTS = "ViewRights";
 public const string ADDRIGHTS = "AddRights";
 public const string EDITRIGHTS = "EditRights";
 public const string DELETERIGHTS = "DeleteRights";
 public const string REPORTRIGHTS = "ReportRights";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct User_Session_Tracking
{
 public const string SESSION_ID = "Session_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string USER_ID = "User_Id";
 public const string DEVICE_TYPE = "Device_Type";
 public const string OS = "OS";
 public const string BROWSER = "Browser";
 public const string IP_ADDRESS = "IP_Address";
 public const string START_TIME = "Start_Time";
 public const string END_TIME = "End_Time";
 public const string LANGUAGE_SELECTED = "Language_Selected";
 public const string VOICE_SELECTED = "Voice_Selected";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Vendor
{
 public const string VENDORID = "VendorId";
 public const string LOCATION_ID = "Location_ID";
 public const string VENDORCODE = "VendorCode";
 public const string VENDORNAME = "VendorName";
 public const string VATREGISTRATIONNO = "VATRegistrationNo";
 public const string CONTACTNAME = "ContactName";
 public const string CONTACTTITLE = "ContactTitle";
 public const string PHONENUMBER = "PhoneNumber";
 public const string EMAIL = "Email";
 public const string ADDRESSLINE1 = "AddressLine1";
 public const string ADDRESSLINE2 = "AddressLine2";
 public const string CITY = "City";
 public const string STATE = "State";
 public const string POSTALCODE = "PostalCode";
 public const string COUNTRY = "Country";
 public const string WEBSITEURL = "WebsiteURL";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Voice
{
 public const string VOICE_ID = "Voice_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string LANGUAGE_CODE = "Language_Code";
 public const string VOICE_NAME = "Voice_Name";
 public const string GENDER = "Gender";
 public const string EMOTION_SUPPORT = "Emotion_Support";
 public const string TTS_ENGINE = "TTS_Engine";
 public const string IS_BETA = "Is_Beta";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
public struct Voice_Preference
{
 public const string PREFERENCE_ID = "Preference_Id";
 public const string LOCATION_ID = "Location_ID";
 public const string USER_ID = "User_Id";
 public const string SPEED = "Speed";
 public const string PITCH = "Pitch";
 public const string EMOTION_MODE = "Emotion_Mode";
 public const string PREFERRED_VOICE = "Preferred_Voice";
 public const string NOTES = "Notes";
 public const string IS_ACTIVE = "Is_Active";
 public const string CREATED_DATE = "Created_Date";
 public const string CREATED_BY = "Created_By";
 public const string MODIFIED_DATE = "Modified_Date";
 public const string MODIFIED_BY = "Modified_By";
 public const string AUDIT_ID = "Audit_Id";
 public const string USER_IP = "User_IP";
 public const string SITE_ID = "Site_Id";
}
}
}
/*****************************************************************************************************************/

