/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, October 3, 2024
Time: 1:20:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
namespace DomainLayer
{
    public static class DomainExtension
    {
        //Interface convertors
        public static IDomain ConvertIDomain(this object Value)
        {
            return (IDomain)Value;
        }
        public static DomainLayer.Asset ConvertAsset(this IDomain Value)
        {
            return (DomainLayer.Asset)Value;
        }
        public static DomainLayer.Process ConvertProcess(this IDomain Value)
        {
            return (DomainLayer.Process)Value;
        }
        public static DomainLayer.Setup ConvertSetup(this IDomain Value)
        {
            return (DomainLayer.Setup)Value;
        }
        public static DomainLayer.Authentication ConvertAuthentication(this IDomain Value)
        {
            return (DomainLayer.Authentication)Value;
        }
        public static DomainLayer.DomainClass ConvertDomainClass(this IDomain Value)
        {
            return (DomainLayer.DomainClass)Value;
        }
    }
}
/*****************************************************************************************************************/

