//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentary_Log
    {
        public long Log_Id { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<long> Feed_Id { get; set; }
        public Nullable<decimal> Engagement_Score { get; set; }
        public Nullable<int> Latency_Millis { get; set; }
        public Nullable<decimal> Sentiment_Score { get; set; }
        public string Feedback_Text { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Commentary_Feed Commentary_Feed { get; set; }
    }
}
