//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentary_Feed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commentary_Feed()
        {
            this.Commentary_Log = new HashSet<Commentary_Log>();
            this.Commentary_Segment = new HashSet<Commentary_Segment>();
        }
    
        public long Feed_Id { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<int> Match_Id { get; set; }
        public string Language_Code { get; set; }
        public string Commentary_Text { get; set; }
        public string Voice_Profile { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Tone { get; set; }
        public string Notes { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentary_Log> Commentary_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentary_Segment> Commentary_Segment { get; set; }
        public virtual Live_Match Live_Match { get; set; }
    }
}
