//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentary_Segment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commentary_Segment()
        {
            this.Retraining_Feedback = new HashSet<Retraining_Feedback>();
        }
    
        public long Segment_Id { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<long> Feed_Id { get; set; }
        public string Segment_Text { get; set; }
        public Nullable<System.DateTime> Segment_Timestamp { get; set; }
        public string Segment_Type { get; set; }
        public string Emotion_Tag { get; set; }
        public string Notes { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Commentary_Feed Commentary_Feed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retraining_Feedback> Retraining_Feedback { get; set; }
    }
}
