//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DALEntities : DbContext
    {
        public DALEntities()
            : base("name=DALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AI_Model> AI_Model { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Commentary_Feed> Commentary_Feed { get; set; }
        public virtual DbSet<Commentary_Log> Commentary_Log { get; set; }
        public virtual DbSet<Commentary_Segment> Commentary_Segment { get; set; }
        public virtual DbSet<Custom_Audience_Segment> Custom_Audience_Segment { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Data_Retention_Policy> Data_Retention_Policy { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Dynamic_Pricing_History> Dynamic_Pricing_History { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Incident_Log> Incident_Log { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Live_Match> Live_Match { get; set; }
        public virtual DbSet<Localization_Token> Localization_Token { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Location_Detail> Location_Detail { get; set; }
        public virtual DbSet<Location_Type> Location_Type { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Match_Stat> Match_Stat { get; set; }
        public virtual DbSet<Model_Training_Job> Model_Training_Job { get; set; }
        public virtual DbSet<PhysicalLocation> PhysicalLocation { get; set; }
        public virtual DbSet<PhysicalLocation_Detail> PhysicalLocation_Detail { get; set; }
        public virtual DbSet<PhysicalLocation_Type> PhysicalLocation_Type { get; set; }
        public virtual DbSet<RealTime_Event_Queue> RealTime_Event_Queue { get; set; }
        public virtual DbSet<Region_Compliance> Region_Compliance { get; set; }
        public virtual DbSet<Retraining_Feedback> Retraining_Feedback { get; set; }
        public virtual DbSet<Screen> Screen { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Sponsor_Message> Sponsor_Message { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<System_Health_Log> System_Health_Log { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Activity_Log> User_Activity_Log { get; set; }
        public virtual DbSet<User_Group> User_Group { get; set; }
        public virtual DbSet<User_Screen_Right> User_Screen_Right { get; set; }
        public virtual DbSet<User_Session_Tracking> User_Session_Tracking { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<Voice> Voice { get; set; }
        public virtual DbSet<Voice_Preference> Voice_Preference { get; set; }
    }
}
