//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long Feedback_Id { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Match_Id { get; set; }
        public string Feedback_Type { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Submitted_At { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Live_Match Live_Match { get; set; }
    }
}
