//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicalLocation()
        {
            this.PhysicalLocation_Detail = new HashSet<PhysicalLocation_Detail>();
        }
    
        public int PhysicalLocation_ID { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public string PhysicalLocationName { get; set; }
        public string Short_Code { get; set; }
        public string Long_Code { get; set; }
        public string Short_Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Parent_PhysicalLocation_ID { get; set; }
        public int PhysicalLocation_Type_Id { get; set; }
        public byte Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<long> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalLocation_Detail> PhysicalLocation_Detail { get; set; }
        public virtual PhysicalLocation_Type PhysicalLocation_Type { get; set; }
    }
}
