//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Screen_Right
    {
        public int UserRightsId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<int> ScreenId { get; set; }
        public Nullable<bool> ViewRights { get; set; }
        public Nullable<bool> AddRights { get; set; }
        public Nullable<bool> EditRights { get; set; }
        public Nullable<bool> DeleteRights { get; set; }
        public Nullable<bool> ReportRights { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<int> Audit_Id { get; set; }
        public string User_IP { get; set; }
        public int Site_Id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Screen Screen { get; set; }
    }
}
