/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
TableName: Group
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
using DataLayer;
using Utility;
namespace DataLayer
{
public partial class Group: DataBase,IData
{
#region IData Members
string IData.InsertQuery()
{
throw new NotImplementedException();
}
string IData.UpdateQuery()
{
throw new NotImplementedException();
}
string IData.DeleteQuery()
{
throw new NotImplementedException();
}
string IData.SelectQuery()
{
throw new NotImplementedException();
}
string IData.SelectAllQuery()
{
throw new NotImplementedException();
}
IDbCommand IData.InsertSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.UpdateSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.DeleteSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectAllSP()
{
 throw new NotImplementedException();
}
void IData.Fill(Hashtable Entity)
{
UserGroupId=Entity[EntityMapper.Group.USERGROUPID].ConvertInteger();
CompanyId=Entity[EntityMapper.Group.COMPANYID].ConvertInteger();
Location_ID=Entity[EntityMapper.Group.LOCATION_ID].ConvertInteger();
GroupName=Entity[EntityMapper.Group.GROUPNAME].ConvertString();
Description=Entity[EntityMapper.Group.DESCRIPTION].ConvertString();
Is_Active=Entity[EntityMapper.Group.IS_ACTIVE].ConvertByte();
Created_Date=Entity[EntityMapper.Group.CREATED_DATE].ConvertDateTime();
Created_By=Entity[EntityMapper.Group.CREATED_BY].ConvertInteger();
Modified_Date=Entity[EntityMapper.Group.MODIFIED_DATE].ConvertDateTime();
Modified_By=Entity[EntityMapper.Group.MODIFIED_BY].ConvertInteger();
Audit_Id=Entity[EntityMapper.Group.AUDIT_ID].ConvertLong();
User_IP=Entity[EntityMapper.Group.USER_IP].ConvertString();
Site_Id=Entity[EntityMapper.Group.SITE_ID].ConvertInteger();
}
void IData.InsertOnSubmit(DALEntities objDataContext, IData Entity)
{
objDataContext.Group.Add(Entity.ConvertGroup());
}
void IData.UpdateOnSubmit(DALEntities objDataContext, IData Entity)
{
Group objEntity = Entity.ConvertGroup();
objDataContext.Group.Attach(objEntity);
}
public IList SelectEntity(DALEntities objDataContext, string Behaviour)
{
try
 {
switch(Behaviour.ToString())
 {
 case DomainMapper.GET_GROUPS_DATA:
  var _Result2 = objDataContext.Group.Select(j =>
new {UserGroupId = j.UserGroupId,
CompanyId = j.CompanyId,
Location_ID = j.Location_ID,
GroupName = j.GroupName,
Description = j.Description,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result2.ToList();
 case DomainMapper.GET_GROUPS:
  var _Result = objDataContext.Group.Select(j =>
new POCO.Group{UserGroupId = j.UserGroupId,
CompanyId = j.CompanyId,
Location_ID = j.Location_ID,
GroupName = j.GroupName,
Description = j.Description,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result.ToList();
case DomainMapper.GET_GROUP_BY_LOCATION_ID:
/* var _Result4 = (from oD in objDataContext.Group
where oD.Location_ID==Location_ID
orderby oD.UserGroupId descending
select new POCO.Group{UserGroupId = oD.UserGroupId,
CompanyId = oD.CompanyId,
Location_ID = oD.Location_ID,
GroupName = oD.GroupName,
Description = oD.Description,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result4.ToList();*/
case DomainMapper.GET_GROUP_BY_ID:
 var _Result1 = (from oD in objDataContext.Group
where oD.UserGroupId==UserGroupId
orderby oD.UserGroupId descending
select new POCO.Group{UserGroupId = oD.UserGroupId,
CompanyId = oD.CompanyId,
Location_ID = oD.Location_ID,
GroupName = oD.GroupName,
Description = oD.Description,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result1;
case DomainMapper.GET_GROUP_BY_ID_DATA:
 var _Result3 = from oD in objDataContext.Group
where oD.UserGroupId==UserGroupId
orderby oD.UserGroupId descending
select new {oD.UserGroupId,oD.CompanyId,oD.Location_ID,oD.GroupName,oD.Description,oD.Is_Active,oD.Created_Date,oD.Created_By,oD.Modified_Date,oD.Modified_By,oD.Audit_Id,oD.User_IP,oD.Site_Id };
ArrayList objList = new ArrayList();
Group objGroup;
foreach (var objGro1 in _Result3)
 {
objGroup = new Group();
objGroup.UserGroupId = objGro1.UserGroupId;
objGroup.CompanyId = objGro1.CompanyId;
objGroup.Location_ID = objGro1.Location_ID;
objGroup.GroupName = objGro1.GroupName;
objGroup.Description = objGro1.Description;
objGroup.Is_Active = objGro1.Is_Active;
objGroup.Created_Date = objGro1.Created_Date;
objGroup.Created_By = objGro1.Created_By;
objGroup.Modified_Date = objGro1.Modified_Date;
objGroup.Modified_By = objGro1.Modified_By;
objGroup.Audit_Id = objGro1.Audit_Id;
objGroup.User_IP = objGro1.User_IP;
objGroup.Site_Id = objGro1.Site_Id;
objList.Add(objGroup);
}
return objList;
default:
return null;
}
}
catch (Exception ex)
{
throw ex;
}
}
void IData.AddChild(IData childEntity)
{
//_ProductDetails.Add((DataLayer.ProductDetail)childEntity);
 throw new NotImplementedException();
}
public void DeleteOnSubmit(DALEntities objDataContext, IData Entity)
{
 //throw new NotImplementedException();
Group objEntity = Entity.ConvertGroup();
objDataContext.Group.Attach(objEntity);
objDataContext.Group.Remove(objEntity);
}
#endregion
}
}
/*****************************************************************************************************************/

