/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
TableName: Incident_Log
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
using DataLayer;
using Utility;
namespace DataLayer
{
public partial class Incident_Log: DataBase,IData
{
#region IData Members
string IData.InsertQuery()
{
throw new NotImplementedException();
}
string IData.UpdateQuery()
{
throw new NotImplementedException();
}
string IData.DeleteQuery()
{
throw new NotImplementedException();
}
string IData.SelectQuery()
{
throw new NotImplementedException();
}
string IData.SelectAllQuery()
{
throw new NotImplementedException();
}
IDbCommand IData.InsertSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.UpdateSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.DeleteSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectAllSP()
{
 throw new NotImplementedException();
}
void IData.Fill(Hashtable Entity)
{
Incident_Id=Entity[EntityMapper.Incident_Log.INCIDENT_ID].ConvertLong();
Location_ID=Entity[EntityMapper.Incident_Log.LOCATION_ID].ConvertInteger();
Component_Name=Entity[EntityMapper.Incident_Log.COMPONENT_NAME].ConvertString();
Incident_Type=Entity[EntityMapper.Incident_Log.INCIDENT_TYPE].ConvertString();
Details=Entity[EntityMapper.Incident_Log.DETAILS].ConvertString();
Detected_At=Entity[EntityMapper.Incident_Log.DETECTED_AT].ConvertDateTime();
Resolved_At=Entity[EntityMapper.Incident_Log.RESOLVED_AT].ConvertDateTime();
Status=Entity[EntityMapper.Incident_Log.STATUS].ConvertString();
Resolved_By=Entity[EntityMapper.Incident_Log.RESOLVED_BY].ConvertInteger();
Notes=Entity[EntityMapper.Incident_Log.NOTES].ConvertString();
Is_Active=Entity[EntityMapper.Incident_Log.IS_ACTIVE].ConvertByte();
Created_Date=Entity[EntityMapper.Incident_Log.CREATED_DATE].ConvertDateTime();
Created_By=Entity[EntityMapper.Incident_Log.CREATED_BY].ConvertInteger();
Modified_Date=Entity[EntityMapper.Incident_Log.MODIFIED_DATE].ConvertDateTime();
Modified_By=Entity[EntityMapper.Incident_Log.MODIFIED_BY].ConvertInteger();
Audit_Id=Entity[EntityMapper.Incident_Log.AUDIT_ID].ConvertLong();
User_IP=Entity[EntityMapper.Incident_Log.USER_IP].ConvertString();
Site_Id=Entity[EntityMapper.Incident_Log.SITE_ID].ConvertInteger();
}
void IData.InsertOnSubmit(DALEntities objDataContext, IData Entity)
{
objDataContext.Incident_Log.Add(Entity.ConvertIncident_Log());
}
void IData.UpdateOnSubmit(DALEntities objDataContext, IData Entity)
{
Incident_Log objEntity = Entity.ConvertIncident_Log();
objDataContext.Incident_Log.Attach(objEntity);
}
public IList SelectEntity(DALEntities objDataContext, string Behaviour)
{
try
 {
switch(Behaviour.ToString())
 {
 case DomainMapper.GET_INCIDENT_LOGS_DATA:
  var _Result2 = objDataContext.Incident_Log.Select(j =>
new {Incident_Id = j.Incident_Id,
Location_ID = j.Location_ID,
Component_Name = j.Component_Name,
Incident_Type = j.Incident_Type,
Details = j.Details,
Detected_At = j.Detected_At,
Resolved_At = j.Resolved_At,
Status = j.Status,
Resolved_By = j.Resolved_By,
Notes = j.Notes,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result2.ToList();
 case DomainMapper.GET_INCIDENT_LOGS:
  var _Result = objDataContext.Incident_Log.Select(j =>
new POCO.Incident_Log{Incident_Id = j.Incident_Id,
Location_ID = j.Location_ID,
Component_Name = j.Component_Name,
Incident_Type = j.Incident_Type,
Details = j.Details,
Detected_At = j.Detected_At,
Resolved_At = j.Resolved_At,
Status = j.Status,
Resolved_By = j.Resolved_By,
Notes = j.Notes,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result.ToList();
case DomainMapper.GET_INCIDENT_LOG_BY_LOCATION_ID:
/* var _Result4 = (from oD in objDataContext.Incident_Log
where oD.Location_ID==Location_ID
orderby oD.Incident_Id descending
select new POCO.Incident_Log{Incident_Id = oD.Incident_Id,
Location_ID = oD.Location_ID,
Component_Name = oD.Component_Name,
Incident_Type = oD.Incident_Type,
Details = oD.Details,
Detected_At = oD.Detected_At,
Resolved_At = oD.Resolved_At,
Status = oD.Status,
Resolved_By = oD.Resolved_By,
Notes = oD.Notes,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result4.ToList();*/
case DomainMapper.GET_INCIDENT_LOG_BY_ID:
 var _Result1 = (from oD in objDataContext.Incident_Log
where oD.Incident_Id==Incident_Id
orderby oD.Incident_Id descending
select new POCO.Incident_Log{Incident_Id = oD.Incident_Id,
Location_ID = oD.Location_ID,
Component_Name = oD.Component_Name,
Incident_Type = oD.Incident_Type,
Details = oD.Details,
Detected_At = oD.Detected_At,
Resolved_At = oD.Resolved_At,
Status = oD.Status,
Resolved_By = oD.Resolved_By,
Notes = oD.Notes,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result1;
case DomainMapper.GET_INCIDENT_LOG_BY_ID_DATA:
 var _Result3 = from oD in objDataContext.Incident_Log
where oD.Incident_Id==Incident_Id
orderby oD.Incident_Id descending
select new {oD.Incident_Id,oD.Location_ID,oD.Component_Name,oD.Incident_Type,oD.Details,oD.Detected_At,oD.Resolved_At,oD.Status,oD.Resolved_By,oD.Notes,oD.Is_Active,oD.Created_Date,oD.Created_By,oD.Modified_Date,oD.Modified_By,oD.Audit_Id,oD.User_IP,oD.Site_Id };
ArrayList objList = new ArrayList();
Incident_Log objIncident_Log;
foreach (var objInc1 in _Result3)
 {
objIncident_Log = new Incident_Log();
objIncident_Log.Incident_Id = objInc1.Incident_Id;
objIncident_Log.Location_ID = objInc1.Location_ID;
objIncident_Log.Component_Name = objInc1.Component_Name;
objIncident_Log.Incident_Type = objInc1.Incident_Type;
objIncident_Log.Details = objInc1.Details;
objIncident_Log.Detected_At = objInc1.Detected_At;
objIncident_Log.Resolved_At = objInc1.Resolved_At;
objIncident_Log.Status = objInc1.Status;
objIncident_Log.Resolved_By = objInc1.Resolved_By;
objIncident_Log.Notes = objInc1.Notes;
objIncident_Log.Is_Active = objInc1.Is_Active;
objIncident_Log.Created_Date = objInc1.Created_Date;
objIncident_Log.Created_By = objInc1.Created_By;
objIncident_Log.Modified_Date = objInc1.Modified_Date;
objIncident_Log.Modified_By = objInc1.Modified_By;
objIncident_Log.Audit_Id = objInc1.Audit_Id;
objIncident_Log.User_IP = objInc1.User_IP;
objIncident_Log.Site_Id = objInc1.Site_Id;
objList.Add(objIncident_Log);
}
return objList;
default:
return null;
}
}
catch (Exception ex)
{
throw ex;
}
}
void IData.AddChild(IData childEntity)
{
//_ProductDetails.Add((DataLayer.ProductDetail)childEntity);
 throw new NotImplementedException();
}
public void DeleteOnSubmit(DALEntities objDataContext, IData Entity)
{
 //throw new NotImplementedException();
Incident_Log objEntity = Entity.ConvertIncident_Log();
objDataContext.Incident_Log.Attach(objEntity);
objDataContext.Incident_Log.Remove(objEntity);
}
#endregion
}
}
/*****************************************************************************************************************/

