/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
TableName: Location_Type
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
using DataLayer;
using Utility;
namespace DataLayer
{
public partial class Location_Type: DataBase,IData
{
#region IData Members
string IData.InsertQuery()
{
throw new NotImplementedException();
}
string IData.UpdateQuery()
{
throw new NotImplementedException();
}
string IData.DeleteQuery()
{
throw new NotImplementedException();
}
string IData.SelectQuery()
{
throw new NotImplementedException();
}
string IData.SelectAllQuery()
{
throw new NotImplementedException();
}
IDbCommand IData.InsertSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.UpdateSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.DeleteSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectAllSP()
{
 throw new NotImplementedException();
}
void IData.Fill(Hashtable Entity)
{
Location_Type_Id=Entity[EntityMapper.Location_Type.LOCATION_TYPE_ID].ConvertInteger();
LocationTypeName=Entity[EntityMapper.Location_Type.LOCATIONTYPENAME].ConvertString();
Description=Entity[EntityMapper.Location_Type.DESCRIPTION].ConvertString();
Parent_Location_Type_ID=Entity[EntityMapper.Location_Type.PARENT_LOCATION_TYPE_ID].ConvertInteger();
Is_Active=Entity[EntityMapper.Location_Type.IS_ACTIVE].ConvertByte();
Created_Date=Entity[EntityMapper.Location_Type.CREATED_DATE].ConvertDateTime();
Created_By=Entity[EntityMapper.Location_Type.CREATED_BY].ConvertInteger();
Modified_Date=Entity[EntityMapper.Location_Type.MODIFIED_DATE].ConvertDateTime();
Modified_By=Entity[EntityMapper.Location_Type.MODIFIED_BY].ConvertInteger();
Audit_Id=Entity[EntityMapper.Location_Type.AUDIT_ID].ConvertLong();
User_IP=Entity[EntityMapper.Location_Type.USER_IP].ConvertString();
Site_Id=Entity[EntityMapper.Location_Type.SITE_ID].ConvertInteger();
}
void IData.InsertOnSubmit(DALEntities objDataContext, IData Entity)
{
objDataContext.Location_Type.Add(Entity.ConvertLocation_Type());
}
void IData.UpdateOnSubmit(DALEntities objDataContext, IData Entity)
{
Location_Type objEntity = Entity.ConvertLocation_Type();
objDataContext.Location_Type.Attach(objEntity);
}
public IList SelectEntity(DALEntities objDataContext, string Behaviour)
{
try
 {
switch(Behaviour.ToString())
 {
 case DomainMapper.GET_LOCATION_TYPES_DATA:
  var _Result2 = objDataContext.Location_Type.Select(j =>
new {Location_Type_Id = j.Location_Type_Id,
LocationTypeName = j.LocationTypeName,
Description = j.Description,
Parent_Location_Type_ID = j.Parent_Location_Type_ID,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result2.ToList();
 case DomainMapper.GET_LOCATION_TYPES:
  var _Result = objDataContext.Location_Type.Select(j =>
new POCO.Location_Type{Location_Type_Id = j.Location_Type_Id,
LocationTypeName = j.LocationTypeName,
Description = j.Description,
Parent_Location_Type_ID = j.Parent_Location_Type_ID,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result.ToList();
case DomainMapper.GET_LOCATION_TYPE_BY_LOCATION_ID:
/* var _Result4 = (from oD in objDataContext.Location_Type
where oD.Location_ID==Location_ID
orderby oD.Location_Type_Id descending
select new POCO.Location_Type{Location_Type_Id = oD.Location_Type_Id,
LocationTypeName = oD.LocationTypeName,
Description = oD.Description,
Parent_Location_Type_ID = oD.Parent_Location_Type_ID,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result4.ToList();*/
case DomainMapper.GET_LOCATION_TYPE_BY_ID:
 var _Result1 = (from oD in objDataContext.Location_Type
where oD.Location_Type_Id==Location_Type_Id
orderby oD.Location_Type_Id descending
select new POCO.Location_Type{Location_Type_Id = oD.Location_Type_Id,
LocationTypeName = oD.LocationTypeName,
Description = oD.Description,
Parent_Location_Type_ID = oD.Parent_Location_Type_ID,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result1;
case DomainMapper.GET_LOCATION_TYPE_BY_ID_DATA:
 var _Result3 = from oD in objDataContext.Location_Type
where oD.Location_Type_Id==Location_Type_Id
orderby oD.Location_Type_Id descending
select new {oD.Location_Type_Id,oD.LocationTypeName,oD.Description,oD.Parent_Location_Type_ID,oD.Is_Active,oD.Created_Date,oD.Created_By,oD.Modified_Date,oD.Modified_By,oD.Audit_Id,oD.User_IP,oD.Site_Id };
ArrayList objList = new ArrayList();
Location_Type objLocation_Type;
foreach (var objLoc1 in _Result3)
 {
objLocation_Type = new Location_Type();
objLocation_Type.Location_Type_Id = objLoc1.Location_Type_Id;
objLocation_Type.LocationTypeName = objLoc1.LocationTypeName;
objLocation_Type.Description = objLoc1.Description;
objLocation_Type.Parent_Location_Type_ID = objLoc1.Parent_Location_Type_ID;
objLocation_Type.Is_Active = objLoc1.Is_Active;
objLocation_Type.Created_Date = objLoc1.Created_Date;
objLocation_Type.Created_By = objLoc1.Created_By;
objLocation_Type.Modified_Date = objLoc1.Modified_Date;
objLocation_Type.Modified_By = objLoc1.Modified_By;
objLocation_Type.Audit_Id = objLoc1.Audit_Id;
objLocation_Type.User_IP = objLoc1.User_IP;
objLocation_Type.Site_Id = objLoc1.Site_Id;
objList.Add(objLocation_Type);
}
return objList;
default:
return null;
}
}
catch (Exception ex)
{
throw ex;
}
}
void IData.AddChild(IData childEntity)
{
//_ProductDetails.Add((DataLayer.ProductDetail)childEntity);
 throw new NotImplementedException();
}
public void DeleteOnSubmit(DALEntities objDataContext, IData Entity)
{
 //throw new NotImplementedException();
Location_Type objEntity = Entity.ConvertLocation_Type();
objDataContext.Location_Type.Attach(objEntity);
objDataContext.Location_Type.Remove(objEntity);
}
#endregion
}
}
/*****************************************************************************************************************/

