/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
TableName: PhysicalLocation
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
using DataLayer;
using Utility;
namespace DataLayer
{
public partial class PhysicalLocation: DataBase,IData
{
#region IData Members
string IData.InsertQuery()
{
throw new NotImplementedException();
}
string IData.UpdateQuery()
{
throw new NotImplementedException();
}
string IData.DeleteQuery()
{
throw new NotImplementedException();
}
string IData.SelectQuery()
{
throw new NotImplementedException();
}
string IData.SelectAllQuery()
{
throw new NotImplementedException();
}
IDbCommand IData.InsertSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.UpdateSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.DeleteSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectAllSP()
{
 throw new NotImplementedException();
}
void IData.Fill(Hashtable Entity)
{
PhysicalLocation_ID=Entity[EntityMapper.PhysicalLocation.PHYSICALLOCATION_ID].ConvertInteger();
Location_ID=Entity[EntityMapper.PhysicalLocation.LOCATION_ID].ConvertInteger();
PhysicalLocationName=Entity[EntityMapper.PhysicalLocation.PHYSICALLOCATIONNAME].ConvertString();
Short_Code=Entity[EntityMapper.PhysicalLocation.SHORT_CODE].ConvertString();
Long_Code=Entity[EntityMapper.PhysicalLocation.LONG_CODE].ConvertString();
Short_Name=Entity[EntityMapper.PhysicalLocation.SHORT_NAME].ConvertString();
Description=Entity[EntityMapper.PhysicalLocation.DESCRIPTION].ConvertString();
Parent_PhysicalLocation_ID=Entity[EntityMapper.PhysicalLocation.PARENT_PHYSICALLOCATION_ID].ConvertInteger();
PhysicalLocation_Type_Id=Entity[EntityMapper.PhysicalLocation.PHYSICALLOCATION_TYPE_ID].ConvertInteger();
Is_Active=Entity[EntityMapper.PhysicalLocation.IS_ACTIVE].ConvertByte();
Created_Date=Entity[EntityMapper.PhysicalLocation.CREATED_DATE].ConvertDateTime();
Created_By=Entity[EntityMapper.PhysicalLocation.CREATED_BY].ConvertInteger();
Modified_Date=Entity[EntityMapper.PhysicalLocation.MODIFIED_DATE].ConvertDateTime();
Modified_By=Entity[EntityMapper.PhysicalLocation.MODIFIED_BY].ConvertInteger();
Audit_Id=Entity[EntityMapper.PhysicalLocation.AUDIT_ID].ConvertLong();
User_IP=Entity[EntityMapper.PhysicalLocation.USER_IP].ConvertString();
Site_Id=Entity[EntityMapper.PhysicalLocation.SITE_ID].ConvertInteger();
}
void IData.InsertOnSubmit(DALEntities objDataContext, IData Entity)
{
objDataContext.PhysicalLocation.Add(Entity.ConvertPhysicalLocation());
}
void IData.UpdateOnSubmit(DALEntities objDataContext, IData Entity)
{
PhysicalLocation objEntity = Entity.ConvertPhysicalLocation();
objDataContext.PhysicalLocation.Attach(objEntity);
}
public IList SelectEntity(DALEntities objDataContext, string Behaviour)
{
try
 {
switch(Behaviour.ToString())
 {
 case DomainMapper.GET_PHYSICALLOCATIONS_DATA:
  var _Result2 = objDataContext.PhysicalLocation.Select(j =>
new {PhysicalLocation_ID = j.PhysicalLocation_ID,
Location_ID = j.Location_ID,
PhysicalLocationName = j.PhysicalLocationName,
Short_Code = j.Short_Code,
Long_Code = j.Long_Code,
Short_Name = j.Short_Name,
Description = j.Description,
Parent_PhysicalLocation_ID = j.Parent_PhysicalLocation_ID,
PhysicalLocation_Type_Id = j.PhysicalLocation_Type_Id,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result2.ToList();
 case DomainMapper.GET_PHYSICALLOCATIONS:
  var _Result = objDataContext.PhysicalLocation.Select(j =>
new POCO.PhysicalLocation{PhysicalLocation_ID = j.PhysicalLocation_ID,
Location_ID = j.Location_ID,
PhysicalLocationName = j.PhysicalLocationName,
Short_Code = j.Short_Code,
Long_Code = j.Long_Code,
Short_Name = j.Short_Name,
Description = j.Description,
Parent_PhysicalLocation_ID = j.Parent_PhysicalLocation_ID,
PhysicalLocation_Type_Id = j.PhysicalLocation_Type_Id,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result.ToList();
case DomainMapper.GET_PHYSICALLOCATION_BY_LOCATION_ID:
/* var _Result4 = (from oD in objDataContext.PhysicalLocation
where oD.Location_ID==Location_ID
orderby oD.PhysicalLocation_ID descending
select new POCO.PhysicalLocation{PhysicalLocation_ID = oD.PhysicalLocation_ID,
Location_ID = oD.Location_ID,
PhysicalLocationName = oD.PhysicalLocationName,
Short_Code = oD.Short_Code,
Long_Code = oD.Long_Code,
Short_Name = oD.Short_Name,
Description = oD.Description,
Parent_PhysicalLocation_ID = oD.Parent_PhysicalLocation_ID,
PhysicalLocation_Type_Id = oD.PhysicalLocation_Type_Id,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result4.ToList();*/
case DomainMapper.GET_PHYSICALLOCATION_BY_ID:
 var _Result1 = (from oD in objDataContext.PhysicalLocation
where oD.PhysicalLocation_ID==PhysicalLocation_ID
orderby oD.PhysicalLocation_ID descending
select new POCO.PhysicalLocation{PhysicalLocation_ID = oD.PhysicalLocation_ID,
Location_ID = oD.Location_ID,
PhysicalLocationName = oD.PhysicalLocationName,
Short_Code = oD.Short_Code,
Long_Code = oD.Long_Code,
Short_Name = oD.Short_Name,
Description = oD.Description,
Parent_PhysicalLocation_ID = oD.Parent_PhysicalLocation_ID,
PhysicalLocation_Type_Id = oD.PhysicalLocation_Type_Id,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result1;
case DomainMapper.GET_PHYSICALLOCATION_BY_ID_DATA:
 var _Result3 = from oD in objDataContext.PhysicalLocation
where oD.PhysicalLocation_ID==PhysicalLocation_ID
orderby oD.PhysicalLocation_ID descending
select new {oD.PhysicalLocation_ID,oD.Location_ID,oD.PhysicalLocationName,oD.Short_Code,oD.Long_Code,oD.Short_Name,oD.Description,oD.Parent_PhysicalLocation_ID,oD.PhysicalLocation_Type_Id,oD.Is_Active,oD.Created_Date,oD.Created_By,oD.Modified_Date,oD.Modified_By,oD.Audit_Id,oD.User_IP,oD.Site_Id };
ArrayList objList = new ArrayList();
PhysicalLocation objPhysicalLocation;
foreach (var objPhy1 in _Result3)
 {
objPhysicalLocation = new PhysicalLocation();
objPhysicalLocation.PhysicalLocation_ID = objPhy1.PhysicalLocation_ID;
objPhysicalLocation.Location_ID = objPhy1.Location_ID;
objPhysicalLocation.PhysicalLocationName = objPhy1.PhysicalLocationName;
objPhysicalLocation.Short_Code = objPhy1.Short_Code;
objPhysicalLocation.Long_Code = objPhy1.Long_Code;
objPhysicalLocation.Short_Name = objPhy1.Short_Name;
objPhysicalLocation.Description = objPhy1.Description;
objPhysicalLocation.Parent_PhysicalLocation_ID = objPhy1.Parent_PhysicalLocation_ID;
objPhysicalLocation.PhysicalLocation_Type_Id = objPhy1.PhysicalLocation_Type_Id;
objPhysicalLocation.Is_Active = objPhy1.Is_Active;
objPhysicalLocation.Created_Date = objPhy1.Created_Date;
objPhysicalLocation.Created_By = objPhy1.Created_By;
objPhysicalLocation.Modified_Date = objPhy1.Modified_Date;
objPhysicalLocation.Modified_By = objPhy1.Modified_By;
objPhysicalLocation.Audit_Id = objPhy1.Audit_Id;
objPhysicalLocation.User_IP = objPhy1.User_IP;
objPhysicalLocation.Site_Id = objPhy1.Site_Id;
objList.Add(objPhysicalLocation);
}
return objList;
default:
return null;
}
}
catch (Exception ex)
{
throw ex;
}
}
void IData.AddChild(IData childEntity)
{
//_ProductDetails.Add((DataLayer.ProductDetail)childEntity);
 throw new NotImplementedException();
}
public void DeleteOnSubmit(DALEntities objDataContext, IData Entity)
{
 //throw new NotImplementedException();
PhysicalLocation objEntity = Entity.ConvertPhysicalLocation();
objDataContext.PhysicalLocation.Attach(objEntity);
objDataContext.PhysicalLocation.Remove(objEntity);
}
#endregion
}
}
/*****************************************************************************************************************/

