/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
TableName: Supplier
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
using DataLayer;
using Utility;
namespace DataLayer
{
public partial class Supplier: DataBase,IData
{
#region IData Members
string IData.InsertQuery()
{
throw new NotImplementedException();
}
string IData.UpdateQuery()
{
throw new NotImplementedException();
}
string IData.DeleteQuery()
{
throw new NotImplementedException();
}
string IData.SelectQuery()
{
throw new NotImplementedException();
}
string IData.SelectAllQuery()
{
throw new NotImplementedException();
}
IDbCommand IData.InsertSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.UpdateSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.DeleteSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectAllSP()
{
 throw new NotImplementedException();
}
void IData.Fill(Hashtable Entity)
{
SupplierId=Entity[EntityMapper.Supplier.SUPPLIERID].ConvertInteger();
Location_ID=Entity[EntityMapper.Supplier.LOCATION_ID].ConvertInteger();
SupplierCode=Entity[EntityMapper.Supplier.SUPPLIERCODE].ConvertString();
SupplierName=Entity[EntityMapper.Supplier.SUPPLIERNAME].ConvertString();
ContactName=Entity[EntityMapper.Supplier.CONTACTNAME].ConvertString();
ContactTitle=Entity[EntityMapper.Supplier.CONTACTTITLE].ConvertString();
PhoneNumber=Entity[EntityMapper.Supplier.PHONENUMBER].ConvertString();
Email=Entity[EntityMapper.Supplier.EMAIL].ConvertString();
AddressLine1=Entity[EntityMapper.Supplier.ADDRESSLINE1].ConvertString();
AddressLine2=Entity[EntityMapper.Supplier.ADDRESSLINE2].ConvertString();
City=Entity[EntityMapper.Supplier.CITY].ConvertString();
State=Entity[EntityMapper.Supplier.STATE].ConvertString();
PostalCode=Entity[EntityMapper.Supplier.POSTALCODE].ConvertString();
Country=Entity[EntityMapper.Supplier.COUNTRY].ConvertString();
WebsiteURL=Entity[EntityMapper.Supplier.WEBSITEURL].ConvertString();
Notes=Entity[EntityMapper.Supplier.NOTES].ConvertString();
Is_Active=Entity[EntityMapper.Supplier.IS_ACTIVE].ConvertByte();
Created_Date=Entity[EntityMapper.Supplier.CREATED_DATE].ConvertDateTime();
Created_By=Entity[EntityMapper.Supplier.CREATED_BY].ConvertInteger();
Modified_Date=Entity[EntityMapper.Supplier.MODIFIED_DATE].ConvertDateTime();
Modified_By=Entity[EntityMapper.Supplier.MODIFIED_BY].ConvertInteger();
Audit_Id=Entity[EntityMapper.Supplier.AUDIT_ID].ConvertLong();
User_IP=Entity[EntityMapper.Supplier.USER_IP].ConvertString();
Site_Id=Entity[EntityMapper.Supplier.SITE_ID].ConvertInteger();
}
void IData.InsertOnSubmit(DALEntities objDataContext, IData Entity)
{
objDataContext.Supplier.Add(Entity.ConvertSupplier());
}
void IData.UpdateOnSubmit(DALEntities objDataContext, IData Entity)
{
Supplier objEntity = Entity.ConvertSupplier();
objDataContext.Supplier.Attach(objEntity);
}
public IList SelectEntity(DALEntities objDataContext, string Behaviour)
{
try
 {
switch(Behaviour.ToString())
 {
 case DomainMapper.GET_SUPPLIERS_DATA:
  var _Result2 = objDataContext.Supplier.Select(j =>
new {SupplierId = j.SupplierId,
Location_ID = j.Location_ID,
SupplierCode = j.SupplierCode,
SupplierName = j.SupplierName,
ContactName = j.ContactName,
ContactTitle = j.ContactTitle,
PhoneNumber = j.PhoneNumber,
Email = j.Email,
AddressLine1 = j.AddressLine1,
AddressLine2 = j.AddressLine2,
City = j.City,
State = j.State,
PostalCode = j.PostalCode,
Country = j.Country,
WebsiteURL = j.WebsiteURL,
Notes = j.Notes,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result2.ToList();
 case DomainMapper.GET_SUPPLIERS:
  var _Result = objDataContext.Supplier.Select(j =>
new POCO.Supplier{SupplierId = j.SupplierId,
Location_ID = j.Location_ID,
SupplierCode = j.SupplierCode,
SupplierName = j.SupplierName,
ContactName = j.ContactName,
ContactTitle = j.ContactTitle,
PhoneNumber = j.PhoneNumber,
Email = j.Email,
AddressLine1 = j.AddressLine1,
AddressLine2 = j.AddressLine2,
City = j.City,
State = j.State,
PostalCode = j.PostalCode,
Country = j.Country,
WebsiteURL = j.WebsiteURL,
Notes = j.Notes,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result.ToList();
case DomainMapper.GET_SUPPLIER_BY_LOCATION_ID:
/* var _Result4 = (from oD in objDataContext.Supplier
where oD.Location_ID==Location_ID
orderby oD.SupplierId descending
select new POCO.Supplier{SupplierId = oD.SupplierId,
Location_ID = oD.Location_ID,
SupplierCode = oD.SupplierCode,
SupplierName = oD.SupplierName,
ContactName = oD.ContactName,
ContactTitle = oD.ContactTitle,
PhoneNumber = oD.PhoneNumber,
Email = oD.Email,
AddressLine1 = oD.AddressLine1,
AddressLine2 = oD.AddressLine2,
City = oD.City,
State = oD.State,
PostalCode = oD.PostalCode,
Country = oD.Country,
WebsiteURL = oD.WebsiteURL,
Notes = oD.Notes,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result4.ToList();*/
case DomainMapper.GET_SUPPLIER_BY_ID:
 var _Result1 = (from oD in objDataContext.Supplier
where oD.SupplierId==SupplierId
orderby oD.SupplierId descending
select new POCO.Supplier{SupplierId = oD.SupplierId,
Location_ID = oD.Location_ID,
SupplierCode = oD.SupplierCode,
SupplierName = oD.SupplierName,
ContactName = oD.ContactName,
ContactTitle = oD.ContactTitle,
PhoneNumber = oD.PhoneNumber,
Email = oD.Email,
AddressLine1 = oD.AddressLine1,
AddressLine2 = oD.AddressLine2,
City = oD.City,
State = oD.State,
PostalCode = oD.PostalCode,
Country = oD.Country,
WebsiteURL = oD.WebsiteURL,
Notes = oD.Notes,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result1;
case DomainMapper.GET_SUPPLIER_BY_ID_DATA:
 var _Result3 = from oD in objDataContext.Supplier
where oD.SupplierId==SupplierId
orderby oD.SupplierId descending
select new {oD.SupplierId,oD.Location_ID,oD.SupplierCode,oD.SupplierName,oD.ContactName,oD.ContactTitle,oD.PhoneNumber,oD.Email,oD.AddressLine1,oD.AddressLine2,oD.City,oD.State,oD.PostalCode,oD.Country,oD.WebsiteURL,oD.Notes,oD.Is_Active,oD.Created_Date,oD.Created_By,oD.Modified_Date,oD.Modified_By,oD.Audit_Id,oD.User_IP,oD.Site_Id };
ArrayList objList = new ArrayList();
Supplier objSupplier;
foreach (var objSup1 in _Result3)
 {
objSupplier = new Supplier();
objSupplier.SupplierId = objSup1.SupplierId;
objSupplier.Location_ID = objSup1.Location_ID;
objSupplier.SupplierCode = objSup1.SupplierCode;
objSupplier.SupplierName = objSup1.SupplierName;
objSupplier.ContactName = objSup1.ContactName;
objSupplier.ContactTitle = objSup1.ContactTitle;
objSupplier.PhoneNumber = objSup1.PhoneNumber;
objSupplier.Email = objSup1.Email;
objSupplier.AddressLine1 = objSup1.AddressLine1;
objSupplier.AddressLine2 = objSup1.AddressLine2;
objSupplier.City = objSup1.City;
objSupplier.State = objSup1.State;
objSupplier.PostalCode = objSup1.PostalCode;
objSupplier.Country = objSup1.Country;
objSupplier.WebsiteURL = objSup1.WebsiteURL;
objSupplier.Notes = objSup1.Notes;
objSupplier.Is_Active = objSup1.Is_Active;
objSupplier.Created_Date = objSup1.Created_Date;
objSupplier.Created_By = objSup1.Created_By;
objSupplier.Modified_Date = objSup1.Modified_Date;
objSupplier.Modified_By = objSup1.Modified_By;
objSupplier.Audit_Id = objSup1.Audit_Id;
objSupplier.User_IP = objSup1.User_IP;
objSupplier.Site_Id = objSup1.Site_Id;
objList.Add(objSupplier);
}
return objList;
default:
return null;
}
}
catch (Exception ex)
{
throw ex;
}
}
void IData.AddChild(IData childEntity)
{
//_ProductDetails.Add((DataLayer.ProductDetail)childEntity);
 throw new NotImplementedException();
}
public void DeleteOnSubmit(DALEntities objDataContext, IData Entity)
{
 //throw new NotImplementedException();
Supplier objEntity = Entity.ConvertSupplier();
objDataContext.Supplier.Attach(objEntity);
objDataContext.Supplier.Remove(objEntity);
}
#endregion
}
}
/*****************************************************************************************************************/

