/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
TableName: User_Group
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
using DataLayer;
using Utility;
namespace DataLayer
{
public partial class User_Group: DataBase,IData
{
#region IData Members
string IData.InsertQuery()
{
throw new NotImplementedException();
}
string IData.UpdateQuery()
{
throw new NotImplementedException();
}
string IData.DeleteQuery()
{
throw new NotImplementedException();
}
string IData.SelectQuery()
{
throw new NotImplementedException();
}
string IData.SelectAllQuery()
{
throw new NotImplementedException();
}
IDbCommand IData.InsertSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.UpdateSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.DeleteSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectSP()
{
 throw new NotImplementedException();
}
IDbCommand IData.SelectAllSP()
{
 throw new NotImplementedException();
}
void IData.Fill(Hashtable Entity)
{
UserGroupRelationId=Entity[EntityMapper.User_Group.USERGROUPRELATIONID].ConvertInteger();
UserId=Entity[EntityMapper.User_Group.USERID].ConvertInteger();
UserGroupId=Entity[EntityMapper.User_Group.USERGROUPID].ConvertInteger();
Is_Active=Entity[EntityMapper.User_Group.IS_ACTIVE].ConvertByte();
Created_Date=Entity[EntityMapper.User_Group.CREATED_DATE].ConvertDateTime();
Created_By=Entity[EntityMapper.User_Group.CREATED_BY].ConvertInteger();
Modified_Date=Entity[EntityMapper.User_Group.MODIFIED_DATE].ConvertDateTime();
Modified_By=Entity[EntityMapper.User_Group.MODIFIED_BY].ConvertInteger();
Audit_Id=Entity[EntityMapper.User_Group.AUDIT_ID].ConvertLong();
User_IP=Entity[EntityMapper.User_Group.USER_IP].ConvertString();
Site_Id=Entity[EntityMapper.User_Group.SITE_ID].ConvertInteger();
}
void IData.InsertOnSubmit(DALEntities objDataContext, IData Entity)
{
objDataContext.User_Group.Add(Entity.ConvertUser_Group());
}
void IData.UpdateOnSubmit(DALEntities objDataContext, IData Entity)
{
User_Group objEntity = Entity.ConvertUser_Group();
objDataContext.User_Group.Attach(objEntity);
}
public IList SelectEntity(DALEntities objDataContext, string Behaviour)
{
try
 {
switch(Behaviour.ToString())
 {
 case DomainMapper.GET_USER_GROUPS_DATA:
  var _Result2 = objDataContext.User_Group.Select(j =>
new {UserGroupRelationId = j.UserGroupRelationId,
UserId = j.UserId,
UserGroupId = j.UserGroupId,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result2.ToList();
 case DomainMapper.GET_USER_GROUPS:
  var _Result = objDataContext.User_Group.Select(j =>
new POCO.User_Group{UserGroupRelationId = j.UserGroupRelationId,
UserId = j.UserId,
UserGroupId = j.UserGroupId,
Is_Active = j.Is_Active,
Created_Date = j.Created_Date,
Created_By = j.Created_By,
Modified_Date = j.Modified_Date,
Modified_By = j.Modified_By,
Audit_Id = j.Audit_Id,
User_IP = j.User_IP,
Site_Id = j.Site_Id
}).ToList();
 return _Result.ToList();
case DomainMapper.GET_USER_GROUP_BY_LOCATION_ID:
/* var _Result4 = (from oD in objDataContext.User_Group
where oD.Location_ID==Location_ID
orderby oD.UserGroupRelationId descending
select new POCO.User_Group{UserGroupRelationId = oD.UserGroupRelationId,
UserId = oD.UserId,
UserGroupId = oD.UserGroupId,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result4.ToList();*/
case DomainMapper.GET_USER_GROUP_BY_ID:
 var _Result1 = (from oD in objDataContext.User_Group
where oD.UserGroupRelationId==UserGroupRelationId
orderby oD.UserGroupRelationId descending
select new POCO.User_Group{UserGroupRelationId = oD.UserGroupRelationId,
UserId = oD.UserId,
UserGroupId = oD.UserGroupId,
Is_Active = oD.Is_Active,
Created_Date = oD.Created_Date,
Created_By = oD.Created_By,
Modified_Date = oD.Modified_Date,
Modified_By = oD.Modified_By,
Audit_Id = oD.Audit_Id,
User_IP = oD.User_IP,
Site_Id = oD.Site_Id
}).ToList();
return _Result1;
case DomainMapper.GET_USER_GROUP_BY_ID_DATA:
 var _Result3 = from oD in objDataContext.User_Group
where oD.UserGroupRelationId==UserGroupRelationId
orderby oD.UserGroupRelationId descending
select new {oD.UserGroupRelationId,oD.UserId,oD.UserGroupId,oD.Is_Active,oD.Created_Date,oD.Created_By,oD.Modified_Date,oD.Modified_By,oD.Audit_Id,oD.User_IP,oD.Site_Id };
ArrayList objList = new ArrayList();
User_Group objUser_Group;
foreach (var objUse1 in _Result3)
 {
objUser_Group = new User_Group();
objUser_Group.UserGroupRelationId = objUse1.UserGroupRelationId;
objUser_Group.UserId = objUse1.UserId;
objUser_Group.UserGroupId = objUse1.UserGroupId;
objUser_Group.Is_Active = objUse1.Is_Active;
objUser_Group.Created_Date = objUse1.Created_Date;
objUser_Group.Created_By = objUse1.Created_By;
objUser_Group.Modified_Date = objUse1.Modified_Date;
objUser_Group.Modified_By = objUse1.Modified_By;
objUser_Group.Audit_Id = objUse1.Audit_Id;
objUser_Group.User_IP = objUse1.User_IP;
objUser_Group.Site_Id = objUse1.Site_Id;
objList.Add(objUser_Group);
}
return objList;
default:
return null;
}
}
catch (Exception ex)
{
throw ex;
}
}
void IData.AddChild(IData childEntity)
{
//_ProductDetails.Add((DataLayer.ProductDetail)childEntity);
 throw new NotImplementedException();
}
public void DeleteOnSubmit(DALEntities objDataContext, IData Entity)
{
 //throw new NotImplementedException();
User_Group objEntity = Entity.ConvertUser_Group();
objDataContext.User_Group.Attach(objEntity);
objDataContext.User_Group.Remove(objEntity);
}
#endregion
}
}
/*****************************************************************************************************************/

