/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Thursday, April 24, 2025
Time: 10:42:00 AM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections;
namespace DataLayer
{
public static class DataExtension
{
 //Interface convertors
public static IData ConvertIData(this object Value)
{
return (IData)Value;
}
public static DataLayer.AI_Model ConvertAI_Model(this object Value)
{
return (DataLayer.AI_Model)Value;
}
public static DataLayer.Category ConvertCategory(this object Value)
{
return (DataLayer.Category)Value;
}
public static DataLayer.Commentary_Feed ConvertCommentary_Feed(this object Value)
{
return (DataLayer.Commentary_Feed)Value;
}
public static DataLayer.Commentary_Log ConvertCommentary_Log(this object Value)
{
return (DataLayer.Commentary_Log)Value;
}
public static DataLayer.Commentary_Segment ConvertCommentary_Segment(this object Value)
{
return (DataLayer.Commentary_Segment)Value;
}
public static DataLayer.Custom_Audience_Segment ConvertCustom_Audience_Segment(this object Value)
{
return (DataLayer.Custom_Audience_Segment)Value;
}
public static DataLayer.Customer ConvertCustomer(this object Value)
{
return (DataLayer.Customer)Value;
}
public static DataLayer.Data_Retention_Policy ConvertData_Retention_Policy(this object Value)
{
return (DataLayer.Data_Retention_Policy)Value;
}
public static DataLayer.Department ConvertDepartment(this object Value)
{
return (DataLayer.Department)Value;
}
public static DataLayer.Dynamic_Pricing_History ConvertDynamic_Pricing_History(this object Value)
{
return (DataLayer.Dynamic_Pricing_History)Value;
}
public static DataLayer.Employee ConvertEmployee(this object Value)
{
return (DataLayer.Employee)Value;
}
public static DataLayer.Feedback ConvertFeedback(this object Value)
{
return (DataLayer.Feedback)Value;
}
public static DataLayer.Group ConvertGroup(this object Value)
{
return (DataLayer.Group)Value;
}
public static DataLayer.Incident_Log ConvertIncident_Log(this object Value)
{
return (DataLayer.Incident_Log)Value;
}
public static DataLayer.Language ConvertLanguage(this object Value)
{
return (DataLayer.Language)Value;
}
public static DataLayer.Live_Match ConvertLive_Match(this object Value)
{
return (DataLayer.Live_Match)Value;
}
public static DataLayer.Localization_Token ConvertLocalization_Token(this object Value)
{
return (DataLayer.Localization_Token)Value;
}
public static DataLayer.Location ConvertLocation(this object Value)
{
return (DataLayer.Location)Value;
}
public static DataLayer.Location_Detail ConvertLocation_Detail(this object Value)
{
return (DataLayer.Location_Detail)Value;
}
public static DataLayer.Location_Type ConvertLocation_Type(this object Value)
{
return (DataLayer.Location_Type)Value;
}
public static DataLayer.Manufacturer ConvertManufacturer(this object Value)
{
return (DataLayer.Manufacturer)Value;
}
public static DataLayer.Match_Stat ConvertMatch_Stat(this object Value)
{
return (DataLayer.Match_Stat)Value;
}
public static DataLayer.Model_Training_Job ConvertModel_Training_Job(this object Value)
{
return (DataLayer.Model_Training_Job)Value;
}
public static DataLayer.PhysicalLocation ConvertPhysicalLocation(this object Value)
{
return (DataLayer.PhysicalLocation)Value;
}
public static DataLayer.PhysicalLocation_Detail ConvertPhysicalLocation_Detail(this object Value)
{
return (DataLayer.PhysicalLocation_Detail)Value;
}
public static DataLayer.PhysicalLocation_Type ConvertPhysicalLocation_Type(this object Value)
{
return (DataLayer.PhysicalLocation_Type)Value;
}
public static DataLayer.RealTime_Event_Queue ConvertRealTime_Event_Queue(this object Value)
{
return (DataLayer.RealTime_Event_Queue)Value;
}
public static DataLayer.Region_Compliance ConvertRegion_Compliance(this object Value)
{
return (DataLayer.Region_Compliance)Value;
}
public static DataLayer.Retraining_Feedback ConvertRetraining_Feedback(this object Value)
{
return (DataLayer.Retraining_Feedback)Value;
}
public static DataLayer.Screen ConvertScreen(this object Value)
{
return (DataLayer.Screen)Value;
}
public static DataLayer.Settings ConvertSetting(this object Value)
{
return (DataLayer.Settings)Value;
}
public static DataLayer.Sponsor_Message ConvertSponsor_Message(this object Value)
{
return (DataLayer.Sponsor_Message)Value;
}
public static DataLayer.SubCategory ConvertSubCategory(this object Value)
{
return (DataLayer.SubCategory)Value;
}
public static DataLayer.Subscription ConvertSubscription(this object Value)
{
return (DataLayer.Subscription)Value;
}
public static DataLayer.Supplier ConvertSupplier(this object Value)
{
return (DataLayer.Supplier)Value;
}
public static DataLayer.System_Health_Log ConvertSystem_Health_Log(this object Value)
{
return (DataLayer.System_Health_Log)Value;
}
public static DataLayer.Tenant ConvertTenant(this object Value)
{
return (DataLayer.Tenant)Value;
}
public static DataLayer.User ConvertUser(this object Value)
{
return (DataLayer.User)Value;
}
public static DataLayer.User_Activity_Log ConvertUser_Activity_Log(this object Value)
{
return (DataLayer.User_Activity_Log)Value;
}
public static DataLayer.User_Group ConvertUser_Group(this object Value)
{
return (DataLayer.User_Group)Value;
}
public static DataLayer.User_Screen_Right ConvertUser_Screen_Right(this object Value)
{
return (DataLayer.User_Screen_Right)Value;
}
public static DataLayer.User_Session_Tracking ConvertUser_Session_Tracking(this object Value)
{
return (DataLayer.User_Session_Tracking)Value;
}
public static DataLayer.Vendor ConvertVendor(this object Value)
{
return (DataLayer.Vendor)Value;
}
public static DataLayer.Voice ConvertVoice(this object Value)
{
return (DataLayer.Voice)Value;
}
public static DataLayer.Voice_Preference ConvertVoice_Preference(this object Value)
{
return (DataLayer.Voice_Preference)Value;
}
}
}
/*****************************************************************************************************************/

