/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Wednesday, July 22, 2015
Time: 2:26:00 PM
/*****************************************************************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
using System.Collections;
using TransactionLayer;
using Utility;
using DataLayer;
namespace DomainLayer
{
    public class DomainClass : DomainBase, IDomain
    {
        public DomainClass()
        {
            base.SetTransaction(TransactionType.EF);
        }
        ~DomainClass()
        {
            base.RemoveTransaction();
        }
        public void AddField<T, K>(T Key, K Value)
        {
            base.Field(Key, Value);
        }
        public void AddRecord(string EntityName)
        {
            base.AddEntity(EntityName);
        }
        public void AddAJAXEntity(string EntityName, Hashtable Entity)
        {
            base.AddAJAXRecord(EntityName, Entity);
        }
        public void AddHASHEntity(string EntityName, Hashtable Entity)
        {
            base.AddHASHRecord(EntityName, Entity);
        }
        public void AddDeleteEntity(DataLayer.IData Entity)
        {
            base.AddDelEntity(Entity);
        }
        public void Submit()
        {
            base.SubmitRecord();
        }
        public void Append()
        {
            base.AppendRecord();
        }
        public void Insert(UseTransaction IsTransaction)
        {
            try
            {
                _TransactionContext.SubmitChanges(Operations.INSERT, IsTransaction);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public void Update(UseTransaction IsTransaction)
        {
            try
            {
                _TransactionContext.SubmitChanges(Operations.UPDATE, IsTransaction);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public void Delete(UseTransaction IsTransaction)
        {
            try
            {
                _TransactionContext.SubmitChanges(Operations.DELETE, IsTransaction);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public void UpdateCurrentContext(UseTransaction IsTransaction)
        {
            try
            {
                _TransactionContext.SubmitChanges(Operations.UPDATE_CURRENT_CONTEXT, IsTransaction);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public IList Load(string EntityName, string Behaviour)
        {
            IData objData;
            try
            {
                objData = GetEntity(EntityName.ConvertString());
                objData.Fill(_Record);
                _Result = _TransactionContext.Load(objData, Behaviour);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objData = null;
                _Record.Clear();
            }
            return _Result;
        }
        public IList DataList
        {
            get
            {
                return _Result;
            }
        }
    }
}
/*****************************************************************************************************************/

