/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Monday, November 11, 2024
Time: 7:12:00 AM
TableName: API_Client
/*****************************************************************************************************************/
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using DomainLayer;
using DataLayer;
using Utility;
using POCO;
using System.Web.Http;
using System.Web.Http.Description;
using System.Diagnostics;
namespace WebAPI
{
/// <summary>
/// Summary description for API_ClientService
/// </summary>
[Authorize]
public class API_ClientController : ApiController
{
private EventLog eventLog;
private DomainContext objContext;
public API_ClientController()
{
eventLog = new EventLog("API_ClientServiceLog", "localhost", "API_ClientService");
}
[HttpGet]
[Route("api/API_Client/GetAPI_ClientsByID/{ID}")]
public POCO.API_Client GetAPI_ClientsByID(long ID)
{
POCO.API_Client items = new POCO.API_Client();
objContext = new DomainContext(new DomainLayer.DomainClass());
objContext.AddField(EntityMapper.API_Client.CLIENTID, ID);
IList responseList = objContext.Load(EntityMapper.Entities.API_CLIENT, DomainMapper.GET_API_CLIENT_BY_ID);
if (responseList != null)
{ if (responseList.Count > 0) { items = responseList.Cast<POCO.API_Client>().ToList()[0]; }}
return items;
}
[HttpGet]
[Route("api/API_Client/GetAPI_Clients")]
[ResponseType(typeof(POCO.API_Client))]
public POCO.API_Client GetAPI_Clients()
{
POCO.API_Client items = new POCO.API_Client();
objContext = new DomainContext(new DomainLayer.DomainClass());
IList responseList = objContext.Load(EntityMapper.Entities.API_CLIENT, DomainMapper.GET_API_CLIENTS);
if (responseList != null)
{ if (responseList.Count > 0) { items.lstAPI_Client = responseList.Cast<POCO.API_Client>().ToList(); }}
return items;
}
[HttpGet]
[Route("api/API_Client/GetAPI_ClientsByLocationID/{ID}")]
[ResponseType(typeof(POCO.API_Client))]
public POCO.API_Client GetAPI_ClientsByLocationID(long ID)
{
POCO.API_Client items = new POCO.API_Client();
objContext = new DomainContext(new DomainLayer.DomainClass());
objContext.AddField(EntityMapper.API_Client.LOCATION_ID, ID);
IList responseList = objContext.Load(EntityMapper.Entities.API_CLIENT, DomainMapper.GET_API_CLIENT_BY_LOCATION_ID);
if (responseList != null)
{ if (responseList.Count > 0) { items.lstAPI_Client = responseList.Cast<POCO.API_Client>().ToList(); }}
return items;
}
[HttpPost]
[Route("api/API_Client/AddAPI_Client")]
public long AddAPI_Client(POCO.API_Client entity)
{
objContext = new DomainContext(new DomainLayer.DomainClass());
try
{
objContext.AddField(EntityMapper.API_Client.CLIENTSECRET, entity.ClientSecret);
objContext.AddField(EntityMapper.API_Client.CLIENTNAME, entity.ClientName);
objContext.AddField(EntityMapper.API_Client.ACTIVE, entity.Active);
objContext.AddRecord(EntityMapper.Entities.API_CLIENT);
objContext.Submit();
objContext.Insert(UseTransaction.NO);
return objContext.BusinessObject.ConvertDomainClass().ID;
}
catch (Exception ex)
{
throw ex;
}
finally
{
objContext = null;
}
}
[HttpPost]
[Route("api/API_Client/UpdateAPI_Client")]
public long UpdateAPI_Client(POCO.API_Client entity)
{
objContext = new DomainContext(new DomainLayer.DomainClass());
try
{
objContext.AddField(EntityMapper.API_Client.CLIENTID, entity.ClientId);
objContext.AddField(EntityMapper.API_Client.CLIENTSECRET, entity.ClientSecret);
objContext.AddField(EntityMapper.API_Client.CLIENTNAME, entity.ClientName);
objContext.AddField(EntityMapper.API_Client.ACTIVE, entity.Active);
objContext.AddRecord(EntityMapper.Entities.API_CLIENT);
objContext.Submit();
objContext.Update(UseTransaction.NO);
return objContext.BusinessObject.ConvertDomainClass().ID;
}
catch (Exception ex)
{
throw ex;
}
finally
{
objContext = null;
}
}
[HttpPost]
[Route("api/API_Client/DeleteAPI_Client")]
public void DeleteAPI_Client(POCO.API_Client entity)
{
objContext = new DomainContext(new DomainLayer.DomainClass());
try
{
objContext.AddField(EntityMapper.API_Client.CLIENTID, entity.ClientId);
objContext.Load(EntityMapper.Entities.API_CLIENT, DomainMapper.GET_API_CLIENT_BY_ID_DATA);
objContext.AddDeleteEntity(objContext.BusinessObject.DataList[0].ConvertAPI_Client());
objContext.Delete(UseTransaction.NO);
}
catch (Exception ex)
{
throw ex;
}
finally
{
objContext = null;
}
}
}
}
/*****************************************************************************************************************/

