/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Monday, November 11, 2024
Time: 7:12:00 AM
TableName: Tenant
/*****************************************************************************************************************/
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using DomainLayer;
using DataLayer;
using Utility;
using POCO;
using System.Web.Http;
using System.Web.Http.Description;
using System.Diagnostics;
namespace WebAPI
{
    /// <summary>
    /// Summary description for TenantService
    /// </summary>
    [Authorize]
    public class TenantController : ApiController
    {
        private EventLog eventLog;
        private DomainContext objContext;
        public TenantController()
        {
            eventLog = new EventLog("TenantServiceLog", "localhost", "TenantService");
        }
        [HttpGet]
        [Route("api/Tenant/GetTenantsByID/{ID}")]
        public POCO.Tenant GetTenantsByID(long ID)
        {
            POCO.Tenant items = new POCO.Tenant();
            objContext = new DomainContext(new DomainLayer.DomainClass());
            objContext.AddField(EntityMapper.Tenant.TENANTID, ID);
            IList responseList = objContext.Load(EntityMapper.Entities.TENANT, DomainMapper.GET_TENANT_BY_ID);
            if (responseList != null)
            { if (responseList.Count > 0) { items = responseList.Cast<POCO.Tenant>().ToList()[0]; } }
            return items;
        }
        [HttpGet]
        [Route("api/Tenant/GetTenants")]
        [ResponseType(typeof(POCO.Tenant))]
        public POCO.Tenant GetTenants()
        {
            POCO.Tenant items = new POCO.Tenant();
            objContext = new DomainContext(new DomainLayer.DomainClass());
            IList responseList = objContext.Load(EntityMapper.Entities.TENANT, DomainMapper.GET_TENANTS);
            if (responseList != null)
            { if (responseList.Count > 0) { items.lstTenant = responseList.Cast<POCO.Tenant>().ToList(); } }
            return items;
        }
        //[HttpGet]
        //[Route("api/Tenant/GetTenantsByLocationID/{ID}")]
        //[ResponseType(typeof(POCO.Tenant))]
        //public POCO.Tenant GetTenantsByLocationID(long ID)
        //{
        //    POCO.Tenant items = new POCO.Tenant();
        //    objContext = new DomainContext(new DomainLayer.DomainClass());
        //    objContext.AddField(EntityMapper.Tenant.LOCATION_ID, ID);
        //    IList responseList = objContext.Load(EntityMapper.Entities.TENANT, DomainMapper.GET_TENANT_BY_LOCATION_ID);
        //    if (responseList != null)
        //    { if (responseList.Count > 0) { items.lstTenant = responseList.Cast<POCO.Tenant>().ToList(); } }
        //    return items;
        //}
        [HttpPost]
        [Route("api/Tenant/AddTenant")]
        public long AddTenant(POCO.Tenant entity)
        {
            objContext = new DomainContext(new DomainLayer.DomainClass());
            try
            {
                objContext.AddField(EntityMapper.Tenant.TENANTSECRET, entity.TenantSecret);
                objContext.AddField(EntityMapper.Tenant.TENANTNAME, entity.TenantName);
                objContext.AddField(EntityMapper.Tenant.CONTACTEMAIL, entity.ContactEmail);
                objContext.AddField(EntityMapper.Tenant.SUBSCRIPTIONID, entity.SubscriptionId);
                objContext.AddField(EntityMapper.Tenant.SUBSCRIPTIONSTARTDATE, entity.SubscriptionStartDate);
                objContext.AddField(EntityMapper.Tenant.SUBSCRIPTIONENDDATE, entity.SubscriptionEndDate);
                objContext.AddField(EntityMapper.Tenant.IS_ACTIVE, entity.Is_Active);
                objContext.AddField(EntityMapper.Tenant.CREATED_DATE, entity.Created_Date);
                objContext.AddField(EntityMapper.Tenant.CREATED_BY, entity.Created_By);
                objContext.AddField(EntityMapper.Tenant.MODIFIED_DATE, entity.Modified_Date);
                objContext.AddField(EntityMapper.Tenant.MODIFIED_BY, entity.Modified_By);
                objContext.AddField(EntityMapper.Tenant.AUDIT_ID, entity.Audit_Id);
                objContext.AddField(EntityMapper.Tenant.USER_IP, entity.User_IP);
                objContext.AddRecord(EntityMapper.Entities.TENANT);
                objContext.Submit();
                objContext.Insert(UseTransaction.NO);
                return objContext.BusinessObject.ConvertDomainClass().ID;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objContext = null;
            }
        }
        [HttpPost]
        [Route("api/Tenant/UpdateTenant")]
        public long UpdateTenant(POCO.Tenant entity)
        {
            objContext = new DomainContext(new DomainLayer.DomainClass());
            try
            {
                objContext.AddField(EntityMapper.Tenant.TENANTID, entity.TenantId);
                objContext.AddField(EntityMapper.Tenant.TENANTSECRET, entity.TenantSecret);
                objContext.AddField(EntityMapper.Tenant.TENANTNAME, entity.TenantName);
                objContext.AddField(EntityMapper.Tenant.CONTACTEMAIL, entity.ContactEmail);
                objContext.AddField(EntityMapper.Tenant.SUBSCRIPTIONID, entity.SubscriptionId);
                objContext.AddField(EntityMapper.Tenant.SUBSCRIPTIONSTARTDATE, entity.SubscriptionStartDate);
                objContext.AddField(EntityMapper.Tenant.SUBSCRIPTIONENDDATE, entity.SubscriptionEndDate);
                objContext.AddField(EntityMapper.Tenant.IS_ACTIVE, entity.Is_Active);
                objContext.AddField(EntityMapper.Tenant.CREATED_DATE, entity.Created_Date);
                objContext.AddField(EntityMapper.Tenant.CREATED_BY, entity.Created_By);
                objContext.AddField(EntityMapper.Tenant.MODIFIED_DATE, entity.Modified_Date);
                objContext.AddField(EntityMapper.Tenant.MODIFIED_BY, entity.Modified_By);
                objContext.AddField(EntityMapper.Tenant.AUDIT_ID, entity.Audit_Id);
                objContext.AddField(EntityMapper.Tenant.USER_IP, entity.User_IP);
                objContext.AddRecord(EntityMapper.Entities.TENANT);
                objContext.Submit();
                objContext.Update(UseTransaction.NO);
                return objContext.BusinessObject.ConvertDomainClass().ID;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objContext = null;
            }
        }
        [HttpPost]
        [Route("api/Tenant/DeleteTenant")]
        public void DeleteTenant(POCO.Tenant entity)
        {
            objContext = new DomainContext(new DomainLayer.DomainClass());
            try
            {
                objContext.AddField(EntityMapper.Tenant.TENANTID, entity.TenantId);
                objContext.Load(EntityMapper.Entities.TENANT, DomainMapper.GET_TENANT_BY_ID_DATA);
                objContext.AddDeleteEntity(objContext.BusinessObject.DataList[0].ConvertTenant());
                objContext.Delete(UseTransaction.NO);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objContext = null;
            }
        }
    }
}
/*****************************************************************************************************************/

