/*****************************************************************************************************************
Author: Code generated by Shinersoft Code Plumber 2008.
Date: Monday, November 11, 2024
Time: 7:12:00 AM
TableName: User
/*****************************************************************************************************************/
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using DomainLayer;
using DataLayer;
using Utility;
using POCO;
using System.Web.Http;
using System.Web.Http.Description;
using System.Diagnostics;
namespace WebAPI
{
    /// <summary>
    /// Summary description for UserService
    /// </summary>
    [Authorize]
    public class UserController : ApiController
    {
        private EventLog eventLog;
        private DomainContext objContext;
        public UserController()
        {
            eventLog = new EventLog("UserServiceLog", "localhost", "UserService");
        }
        [HttpGet]
        [Route("api/User/GetUsersByID/{ID}")]
        public POCO.User GetUsersByID(long ID)
        {
            POCO.User items = new POCO.User();
            objContext = new DomainContext(new DomainLayer.DomainClass());
            objContext.AddField(EntityMapper.User.USERID, ID);
            IList responseList = objContext.Load(EntityMapper.Entities.USER, DomainMapper.GET_USER_BY_ID);
            if (responseList != null)
            { if (responseList.Count > 0) { items = responseList.Cast<POCO.User>().ToList()[0]; } }
            return items;
        }
        [HttpGet]
        [Route("api/User/GetUsers")]
        [ResponseType(typeof(POCO.User))]
        public POCO.User GetUsers()
        {
            POCO.User items = new POCO.User();
            objContext = new DomainContext(new DomainLayer.DomainClass());
            IList responseList = objContext.Load(EntityMapper.Entities.USER, DomainMapper.GET_USERS);
            if (responseList != null)
            { if (responseList.Count > 0) { items.lstUser = responseList.Cast<POCO.User>().ToList(); } }
            return items;
        }
        [HttpGet]
        [Route("api/User/GetUsersByLocationID/{ID}")]
        [ResponseType(typeof(POCO.User))]
        public POCO.User GetUsersByLocationID(long ID)
        {
            POCO.User items = new POCO.User();
            objContext = new DomainContext(new DomainLayer.DomainClass());
            objContext.AddField(EntityMapper.User.LOCATION_ID, ID);
            IList responseList = objContext.Load(EntityMapper.Entities.USER, DomainMapper.GET_USER_BY_LOCATION_ID);
            if (responseList != null)
            { if (responseList.Count > 0) { items.lstUser = responseList.Cast<POCO.User>().ToList(); } }
            return items;
        }
        [HttpPost]
        [Route("api/User/AddUser")]
        public long AddUser(POCO.User entity)
        {
            objContext = new DomainContext(new DomainLayer.DomainClass());
            try
            {
                objContext.AddField(EntityMapper.User.EMPLOYEEID, entity.EmployeeId);
                objContext.AddField(EntityMapper.User.USERGROUPID, entity.UserGroupId);
                objContext.AddField(EntityMapper.User.LOCATION_ID, entity.Location_Id);
                objContext.AddField(EntityMapper.User.USERNAME, entity.UserName);
                objContext.AddField(EntityMapper.User.PASSWORD, entity.Password);
                objContext.AddField(EntityMapper.User.EMAIL, entity.Email);
                objContext.AddField(EntityMapper.User.TEMPPASSWORD, entity.TempPassword);
                objContext.AddField(EntityMapper.User.DATERANGEFROM, entity.DateRangeFrom);
                objContext.AddField(EntityMapper.User.DATERANGETO, entity.DateRangeTo);
                objContext.AddField(EntityMapper.User.IS_ACTIVE, entity.Is_Active);
                objContext.AddField(EntityMapper.User.CREATED_DATE, entity.Created_Date);
                objContext.AddField(EntityMapper.User.CREATED_BY, entity.Created_By);
                objContext.AddField(EntityMapper.User.MODIFIED_DATE, entity.Modified_Date);
                objContext.AddField(EntityMapper.User.MODIFIED_BY, entity.Modified_By);
                objContext.AddField(EntityMapper.User.AUDIT_ID, entity.Audit_Id);
                objContext.AddField(EntityMapper.User.USER_IP, entity.User_IP);
                objContext.AddField(EntityMapper.User.SITE_ID, entity.Site_Id);
                objContext.AddRecord(EntityMapper.Entities.USER);
                objContext.Submit();
                objContext.Insert(UseTransaction.NO);
                return objContext.BusinessObject.ConvertDomainClass().ID;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objContext = null;
            }
        }
        [HttpPost]
        [Route("api/User/UpdateUser")]
        public long UpdateUser(POCO.User entity)
        {
            objContext = new DomainContext(new DomainLayer.DomainClass());
            try
            {
                objContext.AddField(EntityMapper.User.USERID, entity.UserId);
                objContext.AddField(EntityMapper.User.EMPLOYEEID, entity.EmployeeId);
                objContext.AddField(EntityMapper.User.USERGROUPID, entity.UserGroupId);
                objContext.AddField(EntityMapper.User.LOCATION_ID, entity.Location_Id);
                objContext.AddField(EntityMapper.User.USERNAME, entity.UserName);
                objContext.AddField(EntityMapper.User.PASSWORD, entity.Password);
                objContext.AddField(EntityMapper.User.EMAIL, entity.Email);
                objContext.AddField(EntityMapper.User.TEMPPASSWORD, entity.TempPassword);
                objContext.AddField(EntityMapper.User.DATERANGEFROM, entity.DateRangeFrom);
                objContext.AddField(EntityMapper.User.DATERANGETO, entity.DateRangeTo);
                objContext.AddField(EntityMapper.User.IS_ACTIVE, entity.Is_Active);
                objContext.AddField(EntityMapper.User.CREATED_DATE, entity.Created_Date);
                objContext.AddField(EntityMapper.User.CREATED_BY, entity.Created_By);
                objContext.AddField(EntityMapper.User.MODIFIED_DATE, entity.Modified_Date);
                objContext.AddField(EntityMapper.User.MODIFIED_BY, entity.Modified_By);
                objContext.AddField(EntityMapper.User.AUDIT_ID, entity.Audit_Id);
                objContext.AddField(EntityMapper.User.USER_IP, entity.User_IP);
                objContext.AddField(EntityMapper.User.SITE_ID, entity.Site_Id);
                objContext.AddRecord(EntityMapper.Entities.USER);
                objContext.Submit();
                objContext.Update(UseTransaction.NO);
                return objContext.BusinessObject.ConvertDomainClass().ID;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objContext = null;
            }
        }
        [HttpPost]
        [Route("api/User/DeleteUser")]
        public void DeleteUser(POCO.User entity)
        {
            objContext = new DomainContext(new DomainLayer.DomainClass());
            try
            {
                objContext.AddField(EntityMapper.User.USERID, entity.UserId);
                objContext.Load(EntityMapper.Entities.USER, DomainMapper.GET_USER_BY_ID_DATA);
                objContext.AddDeleteEntity(objContext.BusinessObject.DataList[0].ConvertUser());
                objContext.Delete(UseTransaction.NO);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                objContext = null;
            }
        }
    }
}
/*****************************************************************************************************************/

